namespace sa2_hunting_teacher.Knuckles;

public class AquaticMine(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.AquaticMine;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.UnderTheBlueFlame, P2Id.NextToAnOverturnedGhost, P3Id.PlaceWhereFourthPersonBuried, AquaticMine.PieceToHint),
		Set.Create(EnemyId.GuardianOfTheSwitch, P2Id.MCDA, P3Id.InFrontBathingMiniSkull, AquaticMine.PieceToHint),
		Set.Create(P1Id.WoodenWindowOnARoof, P2Id.BehindAFallingTree, P3Id.UnderFlattenedGroundSide, AquaticMine.PieceToHint),
		Set.Create(P1Id.RightEyeOfTheJumboFace, P2Id.BrokenMineCart, P3Id.UnderFlattenedGroundCenter, AquaticMine.PieceToHint),
		Set.Create(P1Id.ThreeFans, P2Id.LeftEyeOnTheJumboFace, P3Id.DangerousPlace, AquaticMine.PieceToHint),
		Set.Create(P1Id.MetalBarrelInLuggageArea, P2Id.NearTheBlueFlameDoor, P3Id.NextToSkullOutOfPlace, AquaticMine.PieceToHint),
		Set.Create(P1Id.SkullPulley, P2Id.NearTheBlueFlameAltar, P3Id.AboveVerticalLineOfSkulls, AquaticMine.PieceToHint),
		Set.Create(P1Id.OnTheTracksOfABrokenMineCart, EnemyId.WaterLevel2HeightLeft, P3Id.GoBackAndForthOnTracks, AquaticMine.PieceToHint),
		Set.Create(P1Id.GhostPulley, P2Id.InsideOfTheOverturnedMineCart, P3Id.GhostPath, AquaticMine.PieceToHint),
		Set.Create(P1Id.InFrontOfSignN2, EnemyId.WaterLevel2HeightRight, P3Id.MovingAndSurroundedByBlueLights, AquaticMine.PieceToHint),
		Set.Create(P1Id.PassagewayToTheLift, P2Id.InTheSkullFenceL2, P3Id.FloatingWithGhosts, AquaticMine.PieceToHint),
		Set.Create(P1Id.SkullPairWearingTie, P2Id.InTheSkullFenceL3, P3Id.ChaseTheSkull, AquaticMine.PieceToHint),
		Set.Create(P1Id.SkullsLookingAtEachOtherInCave, P2Id.AboveAPairOfSkullsWearingTies, P3Id.PathToTheAbyss, AquaticMine.PieceToHint),
		Set.Create(P1Id.InThreeMetalBarrels, P2Id.TalkingSkullsNearTheWindow, P3Id.DigUnderTriangleSkull, AquaticMine.PieceToHint),
		Set.Create(P1Id.OverturnedMineCart, P2Id.UnderTheTriangleSkull, P3Id.MysteriousDoorAtDoor, AquaticMine.PieceToHint),
		Set.Create(P1Id.BehindTwoHeadsGhostRoom, P2Id.InTheTriangleSkull, P3Id.MysteriousDoorAtCart, AquaticMine.PieceToHint),
		Set.Create(P1Id.UnderTheTiltedPillar, P2Id.BrickRoomAlwaysUnderwater, P3Id.BehindASquareTree, AquaticMine.PieceToHint),
		Set.Create(P1Id.AboveTheSkull, P2Id.MetalBarrelWhereGhostsLive, P3Id.HowMakeXWithSkulls, AquaticMine.PieceToHint),
		Set.Create(P1Id.OnTheSteelGhostBeam, P2Id.TheContainerNextToTheJumboSkullNearSkull, P3Id.SkullFacingOtherWay, AquaticMine.PieceToHint),
		Set.Create(P1Id.OnTheSteelSkullBeam, P2Id.TheContainerNextToTheJumboSkullFarSkull, P3Id.MainPillar, AquaticMine.PieceToHint),
		Set.Create(P1Id.OnTheMineCartTracksL2, P2Id.WoodenBoxSteelBeamNear, P3Id.DigOnTheSlope, AquaticMine.PieceToHint),
		Set.Create(P1Id.OnTheMineCartTracksL3, P2Id.WoodenBoxSteelBeamFar, P3Id.DigAtBottomOfSlope, AquaticMine.PieceToHint),
		Set.Create(P1Id.InAnOvenL3Switch, P2Id.ContainerOnTheShelf, P3Id.DigOnTheSlope, AquaticMine.PieceToHint),
		Set.Create(P1Id.InAnOvenL2, P2Id.GhostWindow, P3Id.UnderwaterBrickRoom, AquaticMine.PieceToHint),
		Set.Create(P1Id.InAnOvenL3Fence, P2Id.JailWindow, P3Id.StairShapedBrickRoomLow, AquaticMine.PieceToHint),
		Set.Create(P1Id.BehindTwoHeadsLiftHall, P2Id.SealedWindow, P3Id.StairShapedBrickRoomHigh, AquaticMine.PieceToHint),
		Set.Create(P1Id.AtTheBottomOfMainPillar, P2Id.BetweenTheSkullsFacingEachOther, P3Id.DentedCeilingNear, AquaticMine.PieceToHint),
		Set.Create(P1Id.BottomOfSkullFence, P2Id.EntranceToTheAbyss, P3Id.DentedCeilingFar, AquaticMine.PieceToHint),
		Set.Create(P1Id.CornerOfTheTracks, P2Id.SwitchOnePointFive, P3Id.DentedCeilingNear, AquaticMine.PieceToHint),
		Set.Create(EnemyId.SomethingOtherThanAMineCart, P2Id.ThreeSkullsArguing, P3Id.DentedCeilingFar, AquaticMine.PieceToHint),
		Set.Create(P1Id.EntranceToMCDA, P2Id.UnderVerticalLineSkulls, P3Id.RedFlowersForSkullCouple, AquaticMine.PieceToHint),
		Set.Create(P1Id.BrickRoomAlwaysUnderwater, P2Id.RedFlowersSkullCoupleHigh, P3Id.ThreeFansLeft, AquaticMine.PieceToHint),
		Set.Create(P1Id.DownBelow, P2Id.RedFlowersSkullCoupleLow, P3Id.ThreeFansCenter, AquaticMine.PieceToHint),
		Set.Create(EnemyId.WaterLevel2HeightLeft, P2Id.InFrontOfAFamilyOfSkulls, P3Id.NearTheWall, AquaticMine.PieceToHint),
	];

	public override string ToString() => "Aquatic Mine";

	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(EnemyId.WaterLevel2HeightLeft), "Water level 2 height. (left)" },
		{ Set.EnumKey(EnemyId.WaterLevel2HeightRight), "Water level 2 height. (right)" },
		{ Set.EnumKey(EnemyId.GuardianOfTheSwitch), "Guardian of the switch." },
		{ Set.EnumKey(EnemyId.SomethingOtherThanAMineCart), "Something other than a mine cart?" },
		{ Set.EnumKey(P1Id.UnderTheBlueFlame), "Under the blue flame." },
		{ Set.EnumKey(P1Id.OnTheTracksOfABrokenMineCart), "On the tracks of a broken mine cart." },
		{ Set.EnumKey(P1Id.OnTheSteelSkullBeam), "On the steel skull beam." },
		{ Set.EnumKey(P1Id.SkullPulley), "Skull pulley." },
		{ Set.EnumKey(P1Id.WoodenWindowOnARoof), "Wooden window on a roof." },
		{ Set.EnumKey(P1Id.BehindTwoHeadsLiftHall), "Behind two heads. (lift hall)" },
		{ Set.EnumKey(P1Id.AtTheBottomOfMainPillar), "At the bottom of the main pillar." },
		{ Set.EnumKey(P1Id.InFrontOfSignN2), "In front of sign No. 2." },
		{ Set.EnumKey(P1Id.GhostPulley), "Ghost pulley." },
		{ Set.EnumKey(P1Id.RightEyeOfTheJumboFace), "Right eye of the jumbo face." },
		{ Set.EnumKey(P1Id.PassagewayToTheLift), "Passageway to the \"Water-Powered Lift.\"" },
		{ Set.EnumKey(P1Id.AboveTheSkull), "Above the skull." },
		{ Set.EnumKey(P1Id.UnderTheTiltedPillar), "Under the tilted pillar." },
		{ Set.EnumKey(P1Id.OnTheSteelGhostBeam), "On the steel ghost beam." },
		{ Set.EnumKey(P1Id.BehindTwoHeadsGhostRoom), "Behind two heads. (ghost room)" },
		{ Set.EnumKey(P1Id.OnTheMineCartTracksL2), "On the mine cart tracks. (L2)" },
		{ Set.EnumKey(P1Id.OnTheMineCartTracksL3), "On the mine cart tracks. (L3)" },
		{ Set.EnumKey(P1Id.SkullsLookingAtEachOtherInCave), "Skulls looking at each other in a cave." },
		{ Set.EnumKey(P1Id.CornerOfTheTracks), "The corner of the tracks." },
		{ Set.EnumKey(P1Id.ThreeFans), "Three fans." },
		{ Set.EnumKey(P1Id.BottomOfSkullFence), "At the bottom of the skull fence." },
		{ Set.EnumKey(P1Id.BrickRoomAlwaysUnderwater), "A brick room that's always underwater." },
		{ Set.EnumKey(P1Id.DownBelow), "Down below." },
		{ Set.EnumKey(P1Id.SkullPairWearingTie), "Skull pair wearing a tie near a metal barrel." },
		{ Set.EnumKey(P1Id.InAnOvenL3Switch), "In an oven. (L3 switch)" },
		{ Set.EnumKey(P1Id.InAnOvenL2), "In an oven. (L2)" },
		{ Set.EnumKey(P1Id.InAnOvenL3Fence), "In an oven. (L3 fence)" },
		{ Set.EnumKey(P1Id.MetalBarrelInLuggageArea), "Metal barrel in the luggage area." },
		{ Set.EnumKey(P1Id.OverturnedMineCart), "Overturned mine cart." },
		{ Set.EnumKey(P1Id.EntranceToMCDA), "Entrance to the mine cart dumping area." },
		{ Set.EnumKey(P1Id.InThreeMetalBarrels), "In three metal barrels." },
		{ Set.EnumKey(P2Id.BehindAFallingTree), "Behind a falling tree." },
		{ Set.EnumKey(P2Id.InTheSkullFenceL2), "In the skull fence. (L2)" },
		{ Set.EnumKey(P2Id.InTheSkullFenceL3), "In the skull fence. (L3)" },
		{ Set.EnumKey(P2Id.NextToAnOverturnedGhost), "Next to an overturned ghost." },
		{ Set.EnumKey(P2Id.UnderTheTriangleSkull), "Under the triangle skull." },
		{ Set.EnumKey(P2Id.EntranceToTheAbyss), "Entrance to the abyss." },
		{ Set.EnumKey(P2Id.MCDA), "Mine cart dumping area." },
		{ Set.EnumKey(P2Id.BrickRoomAlwaysUnderwater), "A brick room that's always underwater." },
		{ Set.EnumKey(P2Id.InsideOfTheOverturnedMineCart), "Inside of the overturned mine cart." },
		{ Set.EnumKey(P2Id.BrokenMineCart), "Broken mine cart." },
		{ Set.EnumKey(P2Id.MetalBarrelWhereGhostsLive), "Metal barrel where ghosts live." },
		{ Set.EnumKey(P2Id.TheContainerNextToTheJumboSkullNearSkull), "The container next to the jumbo skull. (near skull)" },
		{ Set.EnumKey(P2Id.TheContainerNextToTheJumboSkullFarSkull), "The container next to the jumbo skull. (far skull)" },
		{ Set.EnumKey(P2Id.WoodenBoxSteelBeamNear), "A wooden box on the steel beam. (near)" },
		{ Set.EnumKey(P2Id.WoodenBoxSteelBeamFar), "A wooden box on the steel beam. (far)" },
		{ Set.EnumKey(P2Id.ContainerOnTheShelf), "A container on the shelf." },
		{ Set.EnumKey(P2Id.AboveAPairOfSkullsWearingTies), "Above a pair of skulls wearing ties." },
		{ Set.EnumKey(P2Id.RedFlowersSkullCoupleHigh), "Red flowers for a skull couple. (high)" },
		{ Set.EnumKey(P2Id.RedFlowersSkullCoupleLow), "Red flowers for a skull couple. (low)" },
		{ Set.EnumKey(P2Id.TalkingSkullsNearTheWindow), "Talking skulls near the window." },
		{ Set.EnumKey(P2Id.GhostWindow), "Ghost window." },
		{ Set.EnumKey(P2Id.JailWindow), "Jail window." },
		{ Set.EnumKey(P2Id.LeftEyeOnTheJumboFace), "Left eye on the jumbo face." },
		{ Set.EnumKey(P2Id.InFrontOfAFamilyOfSkulls), "In front of a family of skulls." },
		{ Set.EnumKey(P2Id.SealedWindow), "Sealed window." },
		{ Set.EnumKey(P2Id.InTheTriangleSkull), "In the triangle skull." },
		{ Set.EnumKey(P2Id.BetweenTheSkullsFacingEachOther), "Between the skulls facing each other." },
		{ Set.EnumKey(P2Id.NearTheBlueFlameDoor), "Near the blue flame. (door)" },
		{ Set.EnumKey(P2Id.NearTheBlueFlameAltar), "Near the blue flame. (altar)" },
		{ Set.EnumKey(P2Id.SwitchOnePointFive), "Switch No. 1.5?" },
		{ Set.EnumKey(P2Id.ThreeSkullsArguing), "Three skulls arguing." },
		{ Set.EnumKey(P2Id.UnderVerticalLineSkulls), "Under the vertical line of skulls." },
		{ Set.EnumKey(P3Id.PlaceWhereFourthPersonBuried), "A place where the fourth person of the group is buried." },
		{ Set.EnumKey(P3Id.MysteriousDoorAtDoor), "In front of a mysterious door. (at door)" },
		{ Set.EnumKey(P3Id.MysteriousDoorAtCart), "In front of a mysterious door. (at cart)" },
		{ Set.EnumKey(P3Id.BehindASquareTree), "Behind a square tree." },
		{ Set.EnumKey(P3Id.InFrontBathingMiniSkull), "In front of the bathing mini-skull." },
		{ Set.EnumKey(P3Id.UnderFlattenedGroundSide), "Under the flattened ground. (side)" },
		{ Set.EnumKey(P3Id.UnderFlattenedGroundCenter), "Under the flattened ground. (center)" },
		{ Set.EnumKey(P3Id.DangerousPlace), "Dangerous place." },
		{ Set.EnumKey(P3Id.NextToSkullOutOfPlace), "Next to a skull that seems out of place." },
		{ Set.EnumKey(P3Id.AboveVerticalLineOfSkulls), "Above the vertical line of skulls." },
		{ Set.EnumKey(P3Id.DigUnderTriangleSkull), "Dig under the triangle skull." },
		{ Set.EnumKey(P3Id.HowMakeXWithSkulls), "How do you make a \"X\" with skulls?" },
		{ Set.EnumKey(P3Id.SkullFacingOtherWay), "The skull that is facing the other way." },
		{ Set.EnumKey(P3Id.DigOnTheSlope), "Dig on the slope." },
		{ Set.EnumKey(P3Id.DigAtBottomOfSlope), "Dig at the bottom of the slope!" },
		{ Set.EnumKey(P3Id.MainPillar), "The main pillar." },
		{ Set.EnumKey(P3Id.MovingAndSurroundedByBlueLights), "It's moving and it's surrounded by blue lights ." },
		{ Set.EnumKey(P3Id.GoBackAndForthOnTracks), "Go back and forth on the tracks." },
		{ Set.EnumKey(P3Id.GhostPath), "Ghost path." },
		{ Set.EnumKey(P3Id.RedFlowersForSkullCouple), "Red flowers for a skull couple." },
		{ Set.EnumKey(P3Id.PathToTheAbyss), "Path to the abyss." },
		{ Set.EnumKey(P3Id.UnderwaterBrickRoom), "Underwater brick room." },
		{ Set.EnumKey(P3Id.FloatingWithGhosts), "Floating with ghosts." },
		{ Set.EnumKey(P3Id.ThreeFansLeft), "Three fans. (left)" },
		{ Set.EnumKey(P3Id.ThreeFansCenter), "Three fans. (center)" },
		{ Set.EnumKey(P3Id.NearTheWall), "Near the wall." },
		{ Set.EnumKey(P3Id.DentedCeilingNear), "Dented ceiling. (near)" },
		{ Set.EnumKey(P3Id.DentedCeilingFar), "Dented ceiling. (far)" },
		{ Set.EnumKey(P3Id.StairShapedBrickRoomLow), "Stair-shaped brick room. (low)" },
		{ Set.EnumKey(P3Id.StairShapedBrickRoomHigh), "Stair-shaped brick room. (high)" },
		{ Set.EnumKey(P3Id.ChaseTheSkull), "Chase the skull!" }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string>();

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(AquaticMine.PieceToHint, AquaticMine.ImpossiblePieces);

	internal enum EnemyId {
		WaterLevel2HeightLeft = 0x000A,
		WaterLevel2HeightRight = 0x010A,
		GuardianOfTheSwitch = 0x020A,
		SomethingOtherThanAMineCart = 0x040A
	}

	internal enum P1Id {
		UnderTheBlueFlame = 0x0001,
		OnTheTracksOfABrokenMineCart = 0x0101,
		OnTheSteelSkullBeam = 0x0301,
		SkullPulley = 0x0401,
		WoodenWindowOnARoof = 0x0501,
		BehindTwoHeadsLiftHall = 0x0601,
		AtTheBottomOfMainPillar = 0x0701,
		InFrontOfSignN2 = 0x0801,
		GhostPulley = 0x0901,
		RightEyeOfTheJumboFace = 0x0A01,
		PassagewayToTheLift = 0x0B01,
		AboveTheSkull = 0x0C01,
		UnderTheTiltedPillar = 0x0D01,
		OnTheSteelGhostBeam = 0x0E01,
		BehindTwoHeadsGhostRoom = 0x0F01,
		OnTheMineCartTracksL2 = 0x1001,
		OnTheMineCartTracksL3 = 0x1101,
		SkullsLookingAtEachOtherInCave = 0x1201,
		CornerOfTheTracks = 0x1301,
		ThreeFans = 0x1401,
		BottomOfSkullFence = 0x1501,
		BrickRoomAlwaysUnderwater = 0x1601,
		DownBelow = 0x1701,
		SkullPairWearingTie = 0x0003,
		InAnOvenL3Switch = 0x0103,
		InAnOvenL2 = 0x0203,
		InAnOvenL3Fence = 0x0303,
		MetalBarrelInLuggageArea = 0x0403,
		OverturnedMineCart = 0x0503,
		EntranceToMCDA = 0x0603,
		InThreeMetalBarrels = 0x0703
	}

	internal enum P2Id {
		BehindAFallingTree = 0x0000,
		InTheSkullFenceL2 = 0x0100,
		InTheSkullFenceL3 = 0x0200,
		NextToAnOverturnedGhost = 0x0300,
		UnderTheTriangleSkull = 0x0400,
		EntranceToTheAbyss = 0x0500,
		MCDA = 0x0600,
		BrickRoomAlwaysUnderwater = 0x0700,
		InsideOfTheOverturnedMineCart = 0x0002,
		BrokenMineCart = 0x0102,
		MetalBarrelWhereGhostsLive = 0x0202,
		TheContainerNextToTheJumboSkullNearSkull = 0x0302,
		TheContainerNextToTheJumboSkullFarSkull = 0x0402,
		WoodenBoxSteelBeamNear = 0x0502,
		WoodenBoxSteelBeamFar = 0x0602,
		ContainerOnTheShelf = 0x0702,
		AboveAPairOfSkullsWearingTies = 0x0005,
		RedFlowersSkullCoupleHigh = 0x0105,
		RedFlowersSkullCoupleLow = 0x0205,
		TalkingSkullsNearTheWindow = 0x0305,
		GhostWindow = 0x0405,
		JailWindow = 0x0505,
		LeftEyeOnTheJumboFace = 0x0605,
		InFrontOfAFamilyOfSkulls = 0x0705,
		SealedWindow = 0x0805,
		InTheTriangleSkull = 0x0905,
		BetweenTheSkullsFacingEachOther = 0x0A05,
		NearTheBlueFlameDoor = 0x0B05,
		NearTheBlueFlameAltar = 0x0C05,
		SwitchOnePointFive = 0x0D05,
		ThreeSkullsArguing = 0x0E05,
		UnderVerticalLineSkulls = 0x0F05
	}

	internal enum P3Id {
		PlaceWhereFourthPersonBuried = 0x0004,
		MysteriousDoorAtDoor = 0x0104,
		MysteriousDoorAtCart = 0x0204,
		BehindASquareTree = 0x0304,
		InFrontBathingMiniSkull = 0x0504,
		UnderFlattenedGroundSide = 0x0604,
		UnderFlattenedGroundCenter = 0x0704,
		DangerousPlace = 0x0804,
		NextToSkullOutOfPlace = 0x0904,
		AboveVerticalLineOfSkulls = 0x0A04,
		DigUnderTriangleSkull = 0x0B04,
		HowMakeXWithSkulls = 0x0C04,
		SkullFacingOtherWay = 0x0D04,
		DigOnTheSlope = 0x0E04,
		DigAtBottomOfSlope = 0x0F04,
		MainPillar = 0x0007,
		MovingAndSurroundedByBlueLights = 0x0107,
		GoBackAndForthOnTracks = 0x0207,
		GhostPath = 0x0307,
		RedFlowersForSkullCouple = 0x0407,
		PathToTheAbyss = 0x0507,
		UnderwaterBrickRoom = 0x0607,
		FloatingWithGhosts = 0x0707,
		ThreeFansLeft = 0x0008,
		ThreeFansCenter = 0x0108,
		NearTheWall = 0x0208,
		DentedCeilingNear = 0x0308,
		DentedCeilingFar = 0x0408,
		StairShapedBrickRoomLow = 0x0508,
		StairShapedBrickRoomHigh = 0x0608,
		ChaseTheSkull = 0x0708
	}
}
