namespace sa2_hunting_teacher.Knuckles;

public class DeathChamber(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.DeathChamber;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.BetweenTheLegs, P2Id.InTheTreasureChest, P3Id.IronProtectsSafe, DeathChamber.PieceToHint),
		Set.Create(P1Id.BlackAndYellowStripes, P2Id.FourLeaves, P3Id.UnderTheRedLight, DeathChamber.PieceToHint),
		Set.Create(P1Id.BugsFood, P2Id.NapeOfTheNeck, P3Id.FloatingBetweenTheFlame, DeathChamber.PieceToHint),
		Set.Create(EnemyId.FireDance, P2Id.PeekABooEggman, P3Id.FlatEggman, DeathChamber.PieceToHint),
		Set.Create(P1Id.EmbarassingPlace, P2Id.ThePlaceWhereTheBugUsedToBe, P3Id.EggmanWithRedNose, DeathChamber.PieceToHint),
		Set.Create(P1Id.E01Core, P2Id.TheOnlyOneWhoIsLookingTheOtherWay, P3Id.OnSquareCliff, DeathChamber.PieceToHint),
		Set.Create(P1Id.PatternedShorts, P2Id.TreasureChestProtectedByScorpion, P3Id.TwoEggmansFacingEachOther, DeathChamber.PieceToHint),
		Set.Create(EnemyId.BurningMad, P2Id.OnRedBall, P3Id.UnderTheRedJewel, DeathChamber.PieceToHint),
		Set.Create(P1Id.JunkStorage, EnemyId.RedBody, P3Id.TwoBugsGatherTwoTrees, DeathChamber.PieceToHint),
		Set.Create(P1Id.EyesBuggedOut, EnemyId.AngryGuy, P3Id.DigInTheAreaInFrontOfTheScorpion, DeathChamber.PieceToHint),
		Set.Create(P1Id.TreasureChestStorage, EnemyId.AngryGuy, P3Id.DigInTheAreaInFrontOfTheScorpion, DeathChamber.PieceToHint),
		Set.Create(P1Id.StinkBug, EnemyId.AngryMan, P3Id.FlyingFishSwimming, DeathChamber.PieceToHint),
		Set.Create(P1Id.CoweringBeetle, P2Id.HugeBug, P3Id.GorillasChase, DeathChamber.PieceToHint),
		Set.Create(P1Id.ItWillAppearWhenCloser, P2Id.ThreeTails, P3Id.AngelsRing, DeathChamber.PieceToHint),
		Set.Create(P1Id.LongVerticalWhiteLine, P2Id.TiltedPicture, P3Id.RescueChao, DeathChamber.PieceToHint),
		Set.Create(EnemyId.WhiteFamily, P2Id.GoldenGoddess, P3Id.GoogleMaps, DeathChamber.PieceToHint),
		Set.Create(P1Id.BatAndHourglass, P2Id.TreasureYouCantOpen, P3Id.WhereTheScorpionUsedToBe, DeathChamber.PieceToHint),
		Set.Create(P1Id.FourSquarePillars, P2Id.BugsDontLikeIt, P3Id.TheOnlyOneLookingDown, DeathChamber.PieceToHint),
		Set.Create(P1Id.SnakesLookingAtEachOther, P2Id.GhostProtectsTheGoddess, P3Id.TwoGuysFarAwayFromEachOther, DeathChamber.PieceToHint),
		Set.Create(P1Id.WhiteDotIndicatesBlue, P2Id.TwoGateKeepers, P3Id.BetweenFourPillars, DeathChamber.PieceToHint),
		Set.Create(P1Id.BatsNest, P2Id.TwoBeautifulWomenOnTheFlame, P3Id.FourSuns, DeathChamber.PieceToHint),
		Set.Create(EnemyId.Sniper, P2Id.RoastedKeys, P3Id.EggmansEyeLevel, DeathChamber.PieceToHint),
		Set.Create(P1Id.BugsDefense, P2Id.BeautyAndTheBeast, P3Id.FlatScorpion, DeathChamber.PieceToHint),
		Set.Create(P1Id.YellowAndBlackStripes, P2Id.GorillasHideout, P3Id.MerryGoRound, DeathChamber.PieceToHint),
		Set.Create(P1Id.MiddleOfRedEyes, P2Id.CornerLight, P3Id.BugsOnPatrol, DeathChamber.PieceToHint),
		Set.Create(P1Id.TwoMouths, P2Id.BatAndScorpion, P3Id.TheAreaThatFourScorpionsAreLookingAt, DeathChamber.PieceToHint),
		Set.Create(EnemyId.BigMarshmallow, P2Id.BugsChatting, P3Id.ConnectTheDots, DeathChamber.PieceToHint),
		Set.Create(P1Id.WaterBug, P2Id.BugsBaby, P3Id.WanderingGhost, DeathChamber.PieceToHint),
		Set.Create(P1Id.GoldenGoddessGreen, P2Id.ScorpionsWhoDontGetAlong, P3Id.FindTheRedScorpionHidingInHole, DeathChamber.PieceToHint),
		Set.Create(P1Id.TwoMouths, P2Id.TriangleFlame, P3Id.AboveOmochao, DeathChamber.PieceToHint),
		Set.Create(P1Id.AboveSmallFlameBlue, P2Id.BugsDontLikeIt, P3Id.ScorpionHidingInABox, DeathChamber.PieceToHint),
		Set.Create(P1Id.ShoeBox, P2Id.OnRedBall, P3Id.ScorpionHidingInABox, DeathChamber.PieceToHint),
		Set.Create(P1Id.MiddleOfRedEyes, P2Id.WhereTheLightUsedToBeShinning, P3Id.AboveOmochao, DeathChamber.PieceToHint),
		Set.Create(P1Id.ThreeContainerBrothers, EnemyId.Sniper, P3Id.AboveOmochao, DeathChamber.PieceToHint),
		Set.Create(P1Id.AboveTheSmallFlame, P2Id.TriangleFlame, P3Id.BetweenFourPillars, DeathChamber.PieceToHint),
		Set.Create(P1Id.GoldenGoddessBlue, P2Id.TreasureChestProtectedByScorpion, P3Id.AboveOmochao, DeathChamber.PieceToHint),
		Set.Create(P1Id.ScorpionTattoo, P2Id.TriangleFlame, P3Id.EggmanWithRedNose, DeathChamber.PieceToHint),
		Set.Create(P1Id.FlyHigherThaBird, P2Id.ScorpionsWhoDontGetAlong, P3Id.WhereTheScorpionUsedToBe, DeathChamber.PieceToHint),
		Set.Create(EnemyId.AngryGuy, P2Id.YouCanSeeItFarAwayCantSeeWhenCloser, P3Id.FindTheRedScorpionHidingInHole, DeathChamber.PieceToHint),
		Set.Create(EnemyId.AngryGuy, P2Id.TwoContainers, P3Id.FindTheRedScorpionHidingInHole, DeathChamber.PieceToHint),
		Set.Create(P1Id.E01Green, P2Id.ScorpionsWhoDontGetAlong, P3Id.IronProtectsSafe, DeathChamber.PieceToHint),
		Set.Create(P1Id.LongVerticalWhiteLine, P2Id.BugsBaby, P3Id.BugTree, DeathChamber.PieceToHint),
		Set.Create(EnemyId.FireDance, P2Id.Heart, P3Id.BugsOnPatrol, DeathChamber.PieceToHint),
		Set.Create(EnemyId.FireDance, P2Id.ScrambleForTheSkull, P3Id.BetweenFourPillars, DeathChamber.PieceToHint),
		Set.Create(P1Id.ScorpionTattoo, P2Id.HugeBlackWall, P3Id.ThereIsAFlameButNoLightCanReachThere, DeathChamber.PieceToHint),
	];

	public override string ToString() => "Death Chamber";

	public override Dictionary<int, string> PieceToHintInstance => DeathChamber.PieceToHint;
	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(EnemyId.RedBody), "Red body." },
		{ Set.EnumKey(EnemyId.Sniper), "Sniper." },
		{ Set.EnumKey(EnemyId.AngryMan), "Angry man." },
		{ Set.EnumKey(EnemyId.FireDance), "Fire dance." },
		{ Set.EnumKey(EnemyId.AngryGuy), "Angry guy." },
		{ Set.EnumKey(EnemyId.BurningMad), "Burning mad..." },
		{ Set.EnumKey(EnemyId.WhiteFamily), "White family." },
		{ Set.EnumKey(EnemyId.BigMarshmallow), "Big marshmallow." },
		{ Set.EnumKey(P1Id.BlackAndYellowStripes), "Black and yellow stripes." },
		{ Set.EnumKey(P1Id.AboveTheSmallFlame), "Above the small flame. (red)" },
		{ Set.EnumKey(P1Id.TwoMouths), "Two mouths." },
		{ Set.EnumKey(P1Id.WaterBug), "Water bug." },
		{ Set.EnumKey(P1Id.SnakesLookingAtEachOther), "Snakes looking at each other." },
		{ Set.EnumKey(P1Id.CoweringBeetle), "Cowering beetle." },
		{ Set.EnumKey(P1Id.BetweenTheLegs), "Between the legs." },
		{ Set.EnumKey(P1Id.BugsFood), "Bug's food." },
		{ Set.EnumKey(P1Id.WhiteDotIndicatesBlue), "White dot indicates blue." },
		{ Set.EnumKey(P1Id.LongVerticalWhiteLine), "Long vertical white line." },
		{ Set.EnumKey(P1Id.AboveSmallFlameBlue), "Above the small flame. (blue)" },
		{ Set.EnumKey(P1Id.BatsNest), "Bat's nest." },
		{ Set.EnumKey(P1Id.BatAndHourglass), "The bat and the hourglass." },
		{ Set.EnumKey(P1Id.FlyHigherThaBird), "Fly higher than a bird!" },
		{ Set.EnumKey(P1Id.E01Green), "E - 01. (green)" },
		{ Set.EnumKey(P1Id.ItWillAppearWhenCloser), "It will appear when you get closer..." },
		{ Set.EnumKey(P1Id.BugsDefense), "Bug's defense." },
		{ Set.EnumKey(P1Id.EyesBuggedOut), "Eyes bugged out...?" },
		{ Set.EnumKey(P1Id.StinkBug), "Stink Bug..." },
		{ Set.EnumKey(P1Id.EmbarassingPlace), "Embarassing place." },
		{ Set.EnumKey(P1Id.E01Core), "E - 01. (core)" },
		{ Set.EnumKey(P1Id.ScorpionTattoo), "Scorpion tattoo." },
		{ Set.EnumKey(P1Id.PatternedShorts), "Patterned shorts." },
		{ Set.EnumKey(P1Id.YellowAndBlackStripes), "Yellow and black stripes." },
		{ Set.EnumKey(P1Id.ThreeContainerBrothers), "Three container brothers." },
		{ Set.EnumKey(P1Id.FourSquarePillars), "Four square pillars." },
		{ Set.EnumKey(P1Id.MiddleOfRedEyes), "In the middle of red eyes." },
		{ Set.EnumKey(P1Id.GoldenGoddessBlue), "Golden goddess. (blue)" },
		{ Set.EnumKey(P1Id.GoldenGoddessGreen), "Golden goddess. (green)" },
		{ Set.EnumKey(P1Id.TreasureChestStorage), "Treasure chest storage." },
		{ Set.EnumKey(P1Id.JunkStorage), "Junk storage." },
		{ Set.EnumKey(P1Id.ShoeBox), "Shoe box." },
		{ Set.EnumKey(P2Id.NapeOfTheNeck), "The nape of the neck." },
		{ Set.EnumKey(P2Id.RoastedKeys), "Roasted keys..." },
		{ Set.EnumKey(P2Id.CornerLight), "Corner light." },
		{ Set.EnumKey(P2Id.TreasureYouCantOpen), "The treasure that you can't open." },
		{ Set.EnumKey(P2Id.GorillasHideout), "Gorilla's hideout." },
		{ Set.EnumKey(P2Id.YouCanSeeItFarAwayCantSeeWhenCloser), "You can see it far away, but you can't see it when you get closer..." },
		{ Set.EnumKey(P2Id.OnRedBall), "On the red ball." },
		{ Set.EnumKey(P2Id.HugeBlackWall), "Huge black wall." },
		{ Set.EnumKey(P2Id.BeautyAndTheBeast), "Beauty and the beast." },
		{ Set.EnumKey(P2Id.TreasureChestProtectedByScorpion), "Treasure chest protected by a scorpion." },
		{ Set.EnumKey(P2Id.InTheTreasureChest), "In the treasure chest." },
		{ Set.EnumKey(P2Id.GoldenGoddess), "Golden goddess." },
		{ Set.EnumKey(P2Id.BugsDontLikeIt), "Bugs don't like it." },
		{ Set.EnumKey(P2Id.TwoContainers), "Two containers." },
		{ Set.EnumKey(P2Id.ThreeTails), "Three tails." },
		{ Set.EnumKey(P2Id.GhostProtectsTheGoddess), "Ghost protects the goddess." },
		{ Set.EnumKey(P2Id.ScrambleForTheSkull), "Scramble for the skull..." },
		{ Set.EnumKey(P2Id.TiltedPicture), "Tilted picture." },
		{ Set.EnumKey(P2Id.BugsChatting), "Bugs chatting." },
		{ Set.EnumKey(P2Id.ThePlaceWhereTheBugUsedToBe), "The place where the bug used to be." },
		{ Set.EnumKey(P2Id.WhereTheLightUsedToBeShinning), "Where the light used to be shinning." },
		{ Set.EnumKey(P2Id.BugsBaby), "Bug's baby." },
		{ Set.EnumKey(P2Id.TriangleFlame), "Triangle flame." },
		{ Set.EnumKey(P2Id.TwoBeautifulWomenOnTheFlame), "Two beautiful women on the flame." },
		{ Set.EnumKey(P2Id.ScorpionsWhoDontGetAlong), "Scorpions who don't get along." },
		{ Set.EnumKey(P2Id.TheOnlyOneWhoIsLookingTheOtherWay), "The only one who is looking the other way..." },
		{ Set.EnumKey(P2Id.FourLeaves), "Four leaves." },
		{ Set.EnumKey(P2Id.PeekABooEggman), "Peek-a-boo Eggman." },
		{ Set.EnumKey(P2Id.TwoGateKeepers), "Two gatekeepers." },
		{ Set.EnumKey(P2Id.HugeBug), "Huge bug." },
		{ Set.EnumKey(P2Id.Heart), "Heart..." },
		{ Set.EnumKey(P2Id.BatAndScorpion), "A bat and a scorpion." },
		{ Set.EnumKey(P3Id.FourSuns), "Four suns look at each other." },
		{ Set.EnumKey(P3Id.WhereTheScorpionUsedToBe), "Where the scorpion used to be." },
		{ Set.EnumKey(P3Id.ScorpionHidingInABox), "Scorpion hiding in a box." },
		{ Set.EnumKey(P3Id.RescueChao), "Rescue Chao who is hunted by a scorpion!" },
		{ Set.EnumKey(P3Id.TheOnlyOneLookingDown), "The only one who is looking down." },
		{ Set.EnumKey(P3Id.BetweenFourPillars), "Between four pillars." },
		{ Set.EnumKey(P3Id.UnderTheRedJewel), "Under the red jewel." },
		{ Set.EnumKey(P3Id.TheAreaThatFourScorpionsAreLookingAt), "The area that four scorpions are looking at." },
		{ Set.EnumKey(P3Id.GorillasChase), "Gorilla's chase." },
		{ Set.EnumKey(P3Id.ConnectTheDots), "Connect the dots." },
		{ Set.EnumKey(P3Id.TwoGuysFarAwayFromEachOther), "Two guys far away from each other." },
		{ Set.EnumKey(P3Id.BugTree), "Bug tree." },
		{ Set.EnumKey(P3Id.DigInTheAreaInFrontOfTheScorpion), "Dig in the area in front of the scorpion!" },
		{ Set.EnumKey(P3Id.TwoEggmansFacingEachOther), "Two Eggmans facing each other." },
		{ Set.EnumKey(P3Id.EggmanWithRedNose), "The Eggman with a red nose." },
		{ Set.EnumKey(P3Id.FindTheRedScorpionHidingInHole), "Find the red scorpion hiding in a hole!" },
		{ Set.EnumKey(P3Id.GoogleMaps), "Go up, then go right and left by the wind power. (google maps)" },
		{ Set.EnumKey(P3Id.BugsOnPatrol), "Bugs on patrol." },
		{ Set.EnumKey(P3Id.ThereIsAFlameButNoLightCanReachThere), "There is a flame, but no light can reach there." },
		{ Set.EnumKey(P3Id.FlyingFishSwimming), "Flying fish swimming in the sand." },
		{ Set.EnumKey(P3Id.WanderingGhost), "Wandering ghost." },
		{ Set.EnumKey(P3Id.MerryGoRound), "Merry-go-round." },
		{ Set.EnumKey(P3Id.AngelsRing), "Angel's ring." },
		{ Set.EnumKey(P3Id.OnSquareCliff), "On the square cliff." },
		{ Set.EnumKey(P3Id.IronProtectsSafe), "Iron protects the safe." },
		{ Set.EnumKey(P3Id.EggmansEyeLevel), "Eggman's eye level." },
		{ Set.EnumKey(P3Id.TwoBugsGatherTwoTrees), "Two bugs who gather in two trees." },
		{ Set.EnumKey(P3Id.FlatEggman), "Flat Eggman." },
		{ Set.EnumKey(P3Id.FloatingBetweenTheFlame), "It's floating between the flames." },
		{ Set.EnumKey(P3Id.AboveOmochao), "Above Omochao." },
		{ Set.EnumKey(P3Id.FlatScorpion), "Flat scorpion." },
		{ Set.EnumKey(P3Id.UnderTheRedLight), "Under the red light." }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string>();

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(DeathChamber.PieceToHint, DeathChamber.ImpossiblePieces);

	internal enum EnemyId {
		RedBody = 0x000A,
		Sniper = 0x020A,
		AngryMan = 0x030A,
		FireDance = 0x060A,
		AngryGuy = 0x070A,
		BurningMad = 0x090A,
		WhiteFamily = 0x0A0A,
		BigMarshmallow = 0x0C0A
	}

	internal enum P1Id {
		BlackAndYellowStripes = 0x0001,
		AboveTheSmallFlame = 0x0101,
		TwoMouths = 0x0201,
		WaterBug = 0x0301,
		SnakesLookingAtEachOther = 0x0401,
		CoweringBeetle = 0x0501,
		BetweenTheLegs = 0x0601,
		BugsFood = 0x0701,
		WhiteDotIndicatesBlue = 0x0801,
		LongVerticalWhiteLine = 0x0901,
		AboveSmallFlameBlue = 0x0A01,
		BatsNest = 0x0B01,
		BatAndHourglass = 0x0C01,
		FlyHigherThaBird = 0x0D01,
		E01Green = 0x0E01,
		ItWillAppearWhenCloser = 0x0F01,
		BugsDefense = 0x1001,
		EyesBuggedOut = 0x1101,
		StinkBug = 0x1201,
		EmbarassingPlace = 0x1301,
		E01Core = 0x1401,
		ScorpionTattoo = 0x1501,
		PatternedShorts = 0x1601,
		YellowAndBlackStripes = 0x1701,
		ThreeContainerBrothers = 0x0003,
		FourSquarePillars = 0x0103,
		MiddleOfRedEyes = 0x0203,
		GoldenGoddessBlue = 0x0303,
		GoldenGoddessGreen = 0x0403,
		TreasureChestStorage = 0x0503,
		JunkStorage = 0x0603,
		ShoeBox = 0x0703
	}

	internal enum P2Id {
		NapeOfTheNeck = 0x0000,
		RoastedKeys = 0x0100,
		CornerLight = 0x0200,
		TreasureYouCantOpen = 0x0300,
		GorillasHideout = 0x0400,
		YouCanSeeItFarAwayCantSeeWhenCloser = 0x0500,
		OnRedBall = 0x0600,
		HugeBlackWall = 0x0700,
		BeautyAndTheBeast = 0x0002,
		TreasureChestProtectedByScorpion = 0x0102,
		InTheTreasureChest = 0x0202,
		GoldenGoddess = 0x0302,
		BugsDontLikeIt = 0x0402,
		TwoContainers = 0x0502,
		ThreeTails = 0x0602,
		GhostProtectsTheGoddess = 0x0702,
		ScrambleForTheSkull = 0x0005,
		TiltedPicture = 0x0105,
		BugsChatting = 0x0205,
		ThePlaceWhereTheBugUsedToBe = 0x0305,
		WhereTheLightUsedToBeShinning = 0x0405,
		BugsBaby = 0x0505,
		TriangleFlame = 0x0605,
		TwoBeautifulWomenOnTheFlame = 0x0705,
		ScorpionsWhoDontGetAlong = 0x0805,
		TheOnlyOneWhoIsLookingTheOtherWay = 0x0905,
		FourLeaves = 0x0A05,
		PeekABooEggman = 0x0B05,
		TwoGateKeepers = 0x0C05,
		HugeBug = 0x0D05,
		Heart = 0x0E05,
		BatAndScorpion = 0x0F05
	}

	internal enum P3Id {
		FourSuns = 0x0004,
		WhereTheScorpionUsedToBe = 0x0104,
		ScorpionHidingInABox = 0x0204,
		RescueChao = 0x0304,
		TheOnlyOneLookingDown = 0x0404,
		BetweenFourPillars = 0x0504,
		UnderTheRedJewel = 0x0604,
		TheAreaThatFourScorpionsAreLookingAt = 0x0704,
		GorillasChase = 0x0804,
		ConnectTheDots = 0x0904,
		TwoGuysFarAwayFromEachOther = 0x0A04,
		BugTree = 0x0B04,
		DigInTheAreaInFrontOfTheScorpion = 0x0C04,
		TwoEggmansFacingEachOther = 0x0D04,
		EggmanWithRedNose = 0x0E04,
		FindTheRedScorpionHidingInHole = 0x0F04,
		GoogleMaps = 0x0007,
		BugsOnPatrol = 0x0107,
		ThereIsAFlameButNoLightCanReachThere = 0x0207,
		FlyingFishSwimming = 0x0307,
		WanderingGhost = 0x0407,
		MerryGoRound = 0x0507,
		AngelsRing = 0x0607,
		OnSquareCliff = 0x0707,
		IronProtectsSafe = 0x0008,
		EggmansEyeLevel = 0x0108,
		TwoBugsGatherTwoTrees = 0x0208,
		FlatEggman = 0x0308,
		FloatingBetweenTheFlame = 0x0408,
		AboveOmochao = 0x0508,
		FlatScorpion = 0x0608,
		UnderTheRedLight = 0x0708
	}
}
