namespace sa2_hunting_teacher.Knuckles;

public class MeteorHerd(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.MeteorHerd;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.ArksHugeStorageAreaNearPlatform, P2Id.BetweenTheMoonAndStars, P3Id.TryDiggingWhileWatchingMoonTop, MeteorHerd.PieceToHint),
		Set.Create(P1Id.ArksHugeStorageAreaFarPlatform, P2Id.TwoAgainstOne, P3Id.TryDiggingWhileWatchingStarsTop, MeteorHerd.PieceToHint),
		Set.Create(P1Id.ArksHugeStorageAreaFarContainer, P2Id.TwoStarsAndOneMoon, P3Id.TryDiggingWhileWatchingBottomHigh, MeteorHerd.PieceToHint),
		Set.Create(P1Id.ArksHugeStorageAreaNearContainer, EnemyId.DangerousWaterDrops, P3Id.TryDiggingWhileWatchingBottomLow, MeteorHerd.PieceToHint),
		Set.Create(EnemyId.DangerousLiquidMiddle, P2Id.ArksHugeStorageArea, P3Id.MovingAroundArksHugeStorageArea, MeteorHerd.PieceToHint),
		Set.Create(P1Id.TwoHugeContainers, P2Id.ForgotToPutItInABigContainer, P3Id.MovingSmoothlyTopOfArk, MeteorHerd.PieceToHint),
		Set.Create(P1Id.InsideContainerBehindAContainer, P2Id.SteelGuardian, P3Id.CenterOfSquareShadow, MeteorHerd.PieceToHint),
		Set.Create(P1Id.AContainerWithinAContainer, P2Id.InFrontOfBigDoorNeverOpensLeft, P3Id.TryDiggingWhileWatchingStarsMiddle, MeteorHerd.PieceToHint),
		Set.Create(P1Id.BetweenTheFloatingContainersNearEnemy, P2Id.OnTopOfSteelDrillingTowerYellow, P3Id.TryDiggingWhileWatchingMoonMiddle, MeteorHerd.PieceToHint),
		Set.Create(P1Id.BetweenTheFloatingContainersUnderBox, P2Id.OnTopOfSteelDrillingTowerGray, P3Id.TryDiggingWhileWatchingStarsBottom, MeteorHerd.PieceToHint),
		Set.Create(P1Id.NearAMoonWithRotatingBeacon, P2Id.InFrontOfBigDoorNeverOpensRight, P3Id.TryDiggingWhileWatchingBottomHigh, MeteorHerd.PieceToHint),
		Set.Create(P1Id.OnRotatingBeaconAboveBlueMoon, P2Id.HighestRotatingBeacon, P3Id.CircleRotatingBeacon, MeteorHerd.PieceToHint),
		Set.Create(P1Id.AboveBlueMoonInFrontOfTankMoon, P2Id.StarAndAMissile, P3Id.BetweenTwoRotatingBeacons, MeteorHerd.PieceToHint),
		Set.Create(P1Id.AboveBlueMoonInFrontOfTankTank, P2Id.MoonAndAMissile, P3Id.FloatingAroundTheMoon, MeteorHerd.PieceToHint),
		Set.Create(P1Id.WhereTwoStonePlatformsJoined, P2Id.StarBetweenThreeArches, P3Id.MiddleOfTheRotatingBeacon, MeteorHerd.PieceToHint),
		Set.Create(P1Id.FastRotatingMeteoriteSmall, P2Id.BehindSomethingPowerful, P3Id.PowerlessByItself, MeteorHerd.PieceToHint),
		Set.Create(P1Id.FastRotatingMeteoriteBig, EnemyId.DangerousWaterDrops, P3Id.SurroundedSpinnerContainers, MeteorHerd.PieceToHint),
		Set.Create(P1Id.NextToRocketPointingAtArk, P2Id.BlackBoxesOnBlackPlatform, P3Id.WanderingBetweenSecondAndThirdLevels, MeteorHerd.PieceToHint),
		Set.Create(P1Id.InTheFloatingContainers, P2Id.TooHeavyToFloat, P3Id.JumpFromTheStarMiddle, MeteorHerd.PieceToHint),
		Set.Create(P1Id.ShortcutRocketLeft, P2Id.NextToARocketAimedAtArk, P3Id.AtTopOfTipOfArk, MeteorHerd.PieceToHint),
		Set.Create(EnemyId.EvilWaterDrops, EnemyId.DangerousWaterDrops, P3Id.ContainerAtTopOfArk, MeteorHerd.PieceToHint),
		Set.Create(EnemyId.DangerousLiquidTop, P2Id.FloatingStoneAboveMoon, P3Id.MovingAroundTheOneFloatingTank, MeteorHerd.PieceToHint),
		Set.Create(EnemyId.GunsMachineProtectingArk, P2Id.UpperFloatingTankNear, P3Id.UseMeteoriteThatFlies, MeteorHerd.PieceToHint),
		Set.Create(P1Id.ShortcutRocketRight, P2Id.UpperFloatingTankFar, P3Id.ThreeTanks, MeteorHerd.PieceToHint),
		Set.Create(P1Id.TheHugeShutterSteelTower, P2Id.SwitchInACage, P3Id.NextToAMiniSteelBeam, MeteorHerd.PieceToHint),
		Set.Create(P1Id.InFrontOfBigDoorNeverOpens, P2Id.LonelyMoon, P3Id.NextToTheMiniSteelBeam, MeteorHerd.PieceToHint),
		Set.Create(P1Id.ZeroPointFive, EnemyId.DangerousLiquidMiddle, P3Id.CageInContainer, MeteorHerd.PieceToHint),
		Set.Create(P1Id.DrillingTower, P2Id.UnderAStar, P3Id.Glimpse, MeteorHerd.PieceToHint),
		Set.Create(P1Id.OnSomethingStrong, P2Id.DigIntoASmallMeteorite, P3Id.BehindAStar, MeteorHerd.PieceToHint),
		Set.Create(P1Id.HotMoltenLava, EnemyId.DangerousLiquidTop, P3Id.JumpFromTheStarNear, MeteorHerd.PieceToHint),
		Set.Create(P1Id.InAWoodenBox, EnemyId.EvilWaterDrops, P3Id.JumpFromTheStarMiddle, MeteorHerd.PieceToHint),
		Set.Create(P1Id.InCenterTriangleStar, EnemyId.GunsMachineProtectingArk, P3Id.JumpFromTheStarFar, MeteorHerd.PieceToHint),
		Set.Create(P1Id.InFrontWeightElevator, P2Id.TheFirstStage, P3Id.NextToAMiniSteelBeam, MeteorHerd.PieceToHint),
		Set.Create(P1Id.BetweenRotatingBeacons, P2Id.AtTheBaseOfTheRotatingBeacon, P3Id.JumpFromTheStarFar, MeteorHerd.PieceToHint),
		Set.Create(P1Id.BetweenNoisyMachines, P2Id.TwinStarsLeft, P3Id.NextToAMiniSteelBeam, MeteorHerd.PieceToHint),
		Set.Create(P1Id.ContainerThatDoesntFloat, P2Id.TwinStarsRight, P3Id.JumpFromTheStarNear, MeteorHerd.PieceToHint),
	];

	public override string ToString() => "Meteor Herd";

	public override Dictionary<int, string> PieceToHintInstance => MeteorHerd.PieceToHint;
	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(EnemyId.DangerousLiquidMiddle), "Dangerous liquid. (middle)" },
		{ Set.EnumKey(EnemyId.DangerousLiquidTop), "Dangerous liquid. (ARK)" },
		{ Set.EnumKey(EnemyId.DangerousWaterDrops), "Dangerous water drops." },
		{ Set.EnumKey(EnemyId.GunsMachineProtectingArk), "A GUN's machine is protecting the ARK." },
		{ Set.EnumKey(EnemyId.EvilWaterDrops), "Evil water drops." },
		{ Set.EnumKey(P1Id.TwoHugeContainers), "Two huge containers." },
		{ Set.EnumKey(P1Id.ArksHugeStorageAreaNearPlatform), "The ARK's huge storage area. (near platform)" },
		{ Set.EnumKey(P1Id.ArksHugeStorageAreaFarPlatform), "The ARK's huge storage area. (far platform)" },
		{ Set.EnumKey(P1Id.ArksHugeStorageAreaFarContainer), "The ARK's huge storage area. (far container)" },
		{ Set.EnumKey(P1Id.ArksHugeStorageAreaNearContainer), "The ARK's huge storage area. (near container)" },
		{ Set.EnumKey(P1Id.InFrontWeightElevator), "In front of the weight elevator." },
		{ Set.EnumKey(P1Id.BetweenTheFloatingContainersNearEnemy), "Between the floating containers. (near enemy)" },
		{ Set.EnumKey(P1Id.NearAMoonWithRotatingBeacon), "Near a moon with a rotating beacon." },
		{ Set.EnumKey(P1Id.BetweenTheFloatingContainersUnderBox), "Between the floating containers. (under box)" },
		{ Set.EnumKey(P1Id.OnRotatingBeaconAboveBlueMoon), "On a rotating beacon above a blue moon." },
		{ Set.EnumKey(P1Id.AboveBlueMoonInFrontOfTankMoon), "Above a blue moon in front of a tank. (moon)" },
		{ Set.EnumKey(P1Id.AboveBlueMoonInFrontOfTankTank), "Above a blue moon in front of a tank. (tank)" },
		{ Set.EnumKey(P1Id.WhereTwoStonePlatformsJoined), "Where two stone platforms are joined." },
		{ Set.EnumKey(P1Id.ShortcutRocketLeft), "In front of the shortcut rocket. (left)" },
		{ Set.EnumKey(P1Id.ShortcutRocketRight), "In front of the shortcut rocket. (right)" },
		{ Set.EnumKey(P1Id.TheHugeShutterSteelTower), "The huge shutter on the steel tower." },
		{ Set.EnumKey(P1Id.InFrontOfBigDoorNeverOpens), "In front of a big door that never opens." },
		{ Set.EnumKey(P1Id.HotMoltenLava), "Hot molten lava below." },
		{ Set.EnumKey(P1Id.ZeroPointFive), "Zero point five." },
		{ Set.EnumKey(P1Id.DrillingTower), "Drilling tower." },
		{ Set.EnumKey(P1Id.OnSomethingStrong), "On something strong." },
		{ Set.EnumKey(P1Id.BetweenRotatingBeacons), "Between the rotating beacons." },
		{ Set.EnumKey(P1Id.BetweenNoisyMachines), "Between the noisy machines." },
		{ Set.EnumKey(P1Id.InCenterTriangleStar), "In the center of a triangle star." },
		{ Set.EnumKey(P1Id.AContainerWithinAContainer), "A container within a container." },
		{ Set.EnumKey(P1Id.InsideContainerBehindAContainer), "Inside a container which is behind a container." },
		{ Set.EnumKey(P1Id.ContainerThatDoesntFloat), "A container that doesn't float." },
		{ Set.EnumKey(P1Id.InTheFloatingContainers), "In the floating containers." },
		{ Set.EnumKey(P1Id.NextToRocketPointingAtArk), "Next to the rocket pointing at the ARK." },
		{ Set.EnumKey(P1Id.FastRotatingMeteoriteSmall), "A fast rotating meteorite. (small)" },
		{ Set.EnumKey(P1Id.FastRotatingMeteoriteBig), "A fast rotating meteorite. (big)" },
		{ Set.EnumKey(P1Id.InAWoodenBox), "In a wooden box." },
		{ Set.EnumKey(P2Id.HighestRotatingBeacon), "The highest rotating beacon." },
		{ Set.EnumKey(P2Id.BlackBoxesOnBlackPlatform), "Black boxes on the black platform." },
		{ Set.EnumKey(P2Id.ForgotToPutItInABigContainer), "Forgot to put it in a big container?" },
		{ Set.EnumKey(P2Id.NextToARocketAimedAtArk), "Next to a rocket aimed at the ARK." },
		{ Set.EnumKey(P2Id.TooHeavyToFloat), "Too heavy to float." },
		{ Set.EnumKey(P2Id.DigIntoASmallMeteorite), "Dig into a small meteorite." },
		{ Set.EnumKey(P2Id.OnTopOfSteelDrillingTowerYellow), "On top of the steel drilling tower. (yellow)" },
		{ Set.EnumKey(P2Id.OnTopOfSteelDrillingTowerGray), "On top of the steel drilling tower. (gray)" },
		{ Set.EnumKey(P2Id.FloatingStoneAboveMoon), "Floating stone above a moon." },
		{ Set.EnumKey(P2Id.ArksHugeStorageArea), "The ARK's huge storage area." },
		{ Set.EnumKey(P2Id.SteelGuardian), "Steel guardian." },
		{ Set.EnumKey(P2Id.UpperFloatingTankNear), "Upper the floating tank! (near)" },
		{ Set.EnumKey(P2Id.UpperFloatingTankFar), "Upper the floating tank! (far)" },
		{ Set.EnumKey(P2Id.UnderAStar), "Under a star." },
		{ Set.EnumKey(P2Id.BetweenTheMoonAndStars), "Between the moon and stars." },
		{ Set.EnumKey(P2Id.TwoAgainstOne), "Two against one!" },
		{ Set.EnumKey(P2Id.TwoStarsAndOneMoon), "Two stars and one moon." },
		{ Set.EnumKey(P2Id.SwitchInACage), "A switch in a cage." },
		{ Set.EnumKey(P2Id.StarAndAMissile), "A star and a missile." },
		{ Set.EnumKey(P2Id.MoonAndAMissile), "A moon and a missile." },
		{ Set.EnumKey(P2Id.LonelyMoon), "Lonely moon." },
		{ Set.EnumKey(P2Id.AtTheBaseOfTheRotatingBeacon), "At the base of the rotating beacon." },
		{ Set.EnumKey(P2Id.StarBetweenThreeArches), "A star between three arches." },
		{ Set.EnumKey(P2Id.BehindSomethingPowerful), "Behind something powerful." },
		{ Set.EnumKey(P2Id.InFrontOfBigDoorNeverOpensLeft), "In front of a big door that never opens. (left)" },
		{ Set.EnumKey(P2Id.InFrontOfBigDoorNeverOpensRight), "In front of a big door that never opens. (right)" },
		{ Set.EnumKey(P2Id.TwinStarsLeft), "Twin stars. (left)" },
		{ Set.EnumKey(P2Id.TheFirstStage), "The first stage." },
		{ Set.EnumKey(P2Id.TwinStarsRight), "Twin stars. (right)" },
		{ Set.EnumKey(P3Id.BehindAStar), "Behind a star." },
		{ Set.EnumKey(P3Id.TryDiggingWhileWatchingMoonTop), "Try digging while watching the moon. (top)" },
		{ Set.EnumKey(P3Id.TryDiggingWhileWatchingStarsTop), "Try digging while watching the stars. (top)" },
		{ Set.EnumKey(P3Id.TryDiggingWhileWatchingBottomHigh), "Try digging while watching the moon. (bottom-high)" },
		{ Set.EnumKey(P3Id.TryDiggingWhileWatchingBottomLow), "Try digging while watching the moon. (bottom-low)" },
		{ Set.EnumKey(P3Id.TryDiggingWhileWatchingStarsMiddle), "Try digging while watching the stars. (middle)" },
		{ Set.EnumKey(P3Id.TryDiggingWhileWatchingMoonMiddle), "Try digging while watching the moon. (middle)" },
		{ Set.EnumKey(P3Id.TryDiggingWhileWatchingStarsBottom), "Try digging while watching the stars. (bottom)" },
		{ Set.EnumKey(P3Id.NextToAMiniSteelBeam), "Next to a mini-steel beam." },
		{ Set.EnumKey(P3Id.NextToTheMiniSteelBeam), "Next to the mini-steel beam." },
		{ Set.EnumKey(P3Id.BetweenTwoRotatingBeacons), "Between two rotating beacons." },
		{ Set.EnumKey(P3Id.PowerlessByItself), "Powerless by itself." },
		{ Set.EnumKey(P3Id.MiddleOfTheRotatingBeacon), "Middle of the rotating beacon." },
		{ Set.EnumKey(P3Id.CenterOfSquareShadow), "Center of a square shadow." },
		{ Set.EnumKey(P3Id.MovingSmoothlyTopOfArk), "Moving smoothly at the top of the ARK." },
		{ Set.EnumKey(P3Id.SurroundedSpinnerContainers), "Surrounded by spinner containers." },
		{ Set.EnumKey(P3Id.MovingAroundArksHugeStorageArea), "Moving around the ARK's huge storage area." },
		{ Set.EnumKey(P3Id.MovingAroundTheOneFloatingTank), "Moving around in front of the one floating tank." },
		{ Set.EnumKey(P3Id.ThreeTanks), "Floating in front of three tanks." },
		{ Set.EnumKey(P3Id.FloatingAroundTheMoon), "Floating around the moon." },
		{ Set.EnumKey(P3Id.CircleRotatingBeacon), "Circle the rotating beacon." },
		{ Set.EnumKey(P3Id.WanderingBetweenSecondAndThirdLevels), "Wandering between the second and third levels." },
		{ Set.EnumKey(P3Id.AtTopOfTipOfArk), "At the top of the tip of the ARK." },
		{ Set.EnumKey(P3Id.ContainerAtTopOfArk), "A container at the top of the ARK." },
		{ Set.EnumKey(P3Id.CageInContainer), "The cage in a container." },
		{ Set.EnumKey(P3Id.Glimpse), "A glimpse of the meteorite." },
		{ Set.EnumKey(P3Id.JumpFromTheStarFar), "Jump from the star! (far)" },
		{ Set.EnumKey(P3Id.JumpFromTheStarMiddle), "Jump from the star! (middle)" },
		{ Set.EnumKey(P3Id.JumpFromTheStarNear), "Jump from the star! (near)" },
		{ Set.EnumKey(P3Id.UseMeteoriteThatFlies), "Use a meteorite that flies when you hit it!" }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string>();

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(MeteorHerd.PieceToHint, MeteorHerd.ImpossiblePieces);

	internal enum EnemyId {
		DangerousLiquidMiddle = 0x000A,
		DangerousLiquidTop = 0x010A,
		DangerousWaterDrops = 0x020A,
		GunsMachineProtectingArk = 0x030A,
		EvilWaterDrops = 0x040A
	}

	internal enum P1Id {
		TwoHugeContainers = 0x0001,
		ArksHugeStorageAreaNearPlatform = 0x0101,
		ArksHugeStorageAreaFarPlatform = 0x0201,
		ArksHugeStorageAreaFarContainer = 0x0301,
		ArksHugeStorageAreaNearContainer = 0x0401,
		InFrontWeightElevator = 0x0501,
		BetweenTheFloatingContainersNearEnemy = 0x0601,
		NearAMoonWithRotatingBeacon = 0x0701,
		BetweenTheFloatingContainersUnderBox = 0x0801,
		OnRotatingBeaconAboveBlueMoon = 0x0901,
		AboveBlueMoonInFrontOfTankMoon = 0x0A01,
		AboveBlueMoonInFrontOfTankTank = 0x0B01,
		WhereTwoStonePlatformsJoined = 0x0C01,
		ShortcutRocketLeft = 0x0D01,
		ShortcutRocketRight = 0x0E01,
		TheHugeShutterSteelTower = 0x0F01,
		InFrontOfBigDoorNeverOpens = 0x1001,
		HotMoltenLava = 0x1101,
		ZeroPointFive = 0x1201,
		DrillingTower = 0x1301,
		OnSomethingStrong = 0x1401,
		BetweenRotatingBeacons = 0x1501,
		BetweenNoisyMachines = 0x1601,
		InCenterTriangleStar = 0x1701,
		AContainerWithinAContainer = 0x0003,
		InsideContainerBehindAContainer = 0x0103,
		ContainerThatDoesntFloat = 0x0203,
		InTheFloatingContainers = 0x0303,
		NextToRocketPointingAtArk = 0x0403,
		FastRotatingMeteoriteSmall = 0x0503,
		FastRotatingMeteoriteBig = 0x0603,
		InAWoodenBox = 0x0703
	}

	internal enum P2Id {
		HighestRotatingBeacon = 0x0000,
		BlackBoxesOnBlackPlatform = 0x0100,
		ForgotToPutItInABigContainer = 0x0200,
		NextToARocketAimedAtArk = 0x0300,
		TooHeavyToFloat = 0x0400,
		DigIntoASmallMeteorite = 0x0500,
		OnTopOfSteelDrillingTowerYellow = 0x0600,
		OnTopOfSteelDrillingTowerGray = 0x0700,
		FloatingStoneAboveMoon = 0x0002,
		ArksHugeStorageArea = 0x0102,
		SteelGuardian = 0x0202,
		UpperFloatingTankNear = 0x0302,
		UpperFloatingTankFar = 0x0402,
		UnderAStar = 0x0005,
		BetweenTheMoonAndStars = 0x0105,
		TwoAgainstOne = 0x0205,
		TwoStarsAndOneMoon = 0x0305,
		SwitchInACage = 0x0405,
		StarAndAMissile = 0x0505,
		MoonAndAMissile = 0x0605,
		LonelyMoon = 0x0705,
		AtTheBaseOfTheRotatingBeacon = 0x0805,
		StarBetweenThreeArches = 0x0905,
		BehindSomethingPowerful = 0x0A05,
		InFrontOfBigDoorNeverOpensLeft = 0x0B05,
		InFrontOfBigDoorNeverOpensRight = 0x0C05,
		TwinStarsLeft = 0x0D05,
		TheFirstStage = 0x0E05,
		TwinStarsRight = 0x0F05
	}

	internal enum P3Id {
		BehindAStar = 0x0004,
		TryDiggingWhileWatchingMoonTop = 0x0104,
		TryDiggingWhileWatchingStarsTop = 0x0204,
		TryDiggingWhileWatchingBottomHigh = 0x0304,
		TryDiggingWhileWatchingBottomLow = 0x0404,
		TryDiggingWhileWatchingStarsMiddle = 0x0504,
		TryDiggingWhileWatchingMoonMiddle = 0x0604,
		TryDiggingWhileWatchingStarsBottom = 0x0704,
		NextToAMiniSteelBeam = 0x0804,
		NextToTheMiniSteelBeam = 0x0904,
		BetweenTwoRotatingBeacons = 0x0B04,
		PowerlessByItself = 0x0D04,
		MiddleOfTheRotatingBeacon = 0x0E04,
		CenterOfSquareShadow = 0x0F04,
		MovingSmoothlyTopOfArk = 0x0007,
		SurroundedSpinnerContainers = 0x0107,
		MovingAroundArksHugeStorageArea = 0x0207,
		MovingAroundTheOneFloatingTank = 0x0307,
		ThreeTanks = 0x0407,
		FloatingAroundTheMoon = 0x0507,
		CircleRotatingBeacon = 0x0607,
		WanderingBetweenSecondAndThirdLevels = 0x0707,
		AtTopOfTipOfArk = 0x0008,
		ContainerAtTopOfArk = 0x0108,
		CageInContainer = 0x0208,
		Glimpse = 0x0308,
		JumpFromTheStarFar = 0x0408,
		JumpFromTheStarMiddle = 0x0508,
		JumpFromTheStarNear = 0x0608,
		UseMeteoriteThatFlies = 0x0708
	}
}
