namespace sa2_hunting_teacher.Knuckles;

public class PumpkinHill(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.PumpkinHill;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.UnderTheChimneyNear, P2Id.PumpkinSnowman, P3Id.ThreeBrothersTombstone, PumpkinHill.PieceToHint),
		Set.Create(P1Id.UnderTheChimneyFar, P2Id.UnderAChimney, P3Id.LostPumpkin, PumpkinHill.PieceToHint),
		Set.Create(P1Id.TurnsButDoesntTurn, P2Id.UnderTheChimney, P3Id.InTheCenterOfATriangle, PumpkinHill.PieceToHint),
		Set.Create(EnemyId.KingOfTheHill, P2Id.YouCanSeeItButYouCantTakeIt, P3Id.TerribleSkullBuried, PumpkinHill.PieceToHint),
		Set.Create(P1Id.SecondSkullFromTheTopLeft, P2Id.ThereIsOnlyOneOnTheCliff, P3Id.StepBackAndWaitNextArrival, PumpkinHill.PieceToHint),
		Set.Create(P1Id.SecondSkullFromTheTopRight, P2Id.YouCanSeeItButYouCantTakeIt, P3Id.TerribleSkullBuried, PumpkinHill.PieceToHint),
		Set.Create(P1Id.SkullsOnTheRightAndLeft, P2Id.ColdIronBars, P3Id.YouCanSeeItButYouCantTakeIt, PumpkinHill.PieceToHint),
		Set.Create(P1Id.PathLinedWithRings, P2Id.ScrambleForTheEmeralds, P3Id.WanderAroundInACircle, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ScrambleForTheEmeralds, P2Id.PumpkinsWhoDontGetAlong, P3Id.WanderAroundInACircleDots, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ItsFloorButAlsoCeilingQuestion, P2Id.PlaceYouCantJump, P3Id.BeardedMountain, PumpkinHill.PieceToHint),
		Set.Create(P1Id.TwinHuts, P2Id.TwinSkulls, P3Id.PlaceWhereFlamesCross, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ForgottenHutGhost, P2Id.SadEyedPumpkinPumpkin, P3Id.EndlessJourney, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ForgottenHutChurch, P2Id.SadEyedPumpkinGhost, P3Id.OnPatrol, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ShadyPlace, P2Id.UnderTheTracks, P3Id.SadEyedPumpkin, PumpkinHill.PieceToHint),
		Set.Create(EnemyId.ThreeBrothersTombstone, P2Id.TombstoneNearSomeGrass, P3Id.PlaceWhereYouCanHearTheHornPumpkin, PumpkinHill.PieceToHint),
		Set.Create(P1Id.TombstoneBySomeGrass, P2Id.LaughingPumpkin, P3Id.PlaceYouCanHearTheHorn, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ItsAFloorAndAlsoACeilingPeriod, P2Id.ChimneyNearSomeGrass, P3Id.PlaceWhereYouCanHearTheHornChurch, PumpkinHill.PieceToHint),
		Set.Create(P1Id.TellsTime, P2Id.ItsAboutToFallOff, P3Id.SomethingBadGhost, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ItsAboutToFallOff, P2Id.ScarcrowsHouse, P3Id.SomethingBadChurch, PumpkinHill.PieceToHint),
		Set.Create(P1Id.VeryHighUp, P2Id.TheRocketPath, P3Id.ThreeAgainstThreeStaringAtEachOther, PumpkinHill.PieceToHint),
		Set.Create(P1Id.PathOfTheGhostTrain, P2Id.ThreeMetalBarrels, P3Id.ThreeScarecrowBrothers, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ThreeMetalBarrels, P2Id.GhostTrainStation, P3Id.StuffedNose, PumpkinHill.PieceToHint),
		Set.Create(P1Id.TheSkullMarksTheSpot, P2Id.ThePersonYouAreWaitingForArrived, P3Id.AngelsRing, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ThreeFacedGhostQuestion, P2Id.ThreeBrothersTombstoneBuried, P3Id.KingOfTheHill, PumpkinHill.PieceToHint),
		Set.Create(P1Id.TheTombstoneGuardedByFourSkulls, EnemyId.KingOfTheHill, P3Id.GhostPumpkinNecklace, PumpkinHill.PieceToHint),
		Set.Create(P1Id.PumpkinFamily, P2Id.SleeplessHouse, P3Id.MissilePath, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ThreeFootGap, P2Id.SleepWithTheDeadRocket, P3Id.NoiseUpstairsAndDown, PumpkinHill.PieceToHint),
		Set.Create(P1Id.FarmHouse, P2Id.SleepWithTheDeadRings, P3Id.FlattenedGrass, PumpkinHill.PieceToHint),
		Set.Create(P1Id.LaughingIntoTears, P2Id.SleepWithTheDeadIsland, P3Id.PumpkinWithCreepySmileLookingAt, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ThreeSkullBrothers, P2Id.LonelyTombstone, P3Id.DangerousMaterial, PumpkinHill.PieceToHint),
		Set.Create(P1Id.DoubleContainersPumpkin, P2Id.SleepBehindAPumpkin, P3Id.DangerousMaterial, PumpkinHill.PieceToHint),
		Set.Create(P1Id.DoubleContainersChurch, P2Id.PumpkinFamily, P3Id.GhostTrainsGuidePost, PumpkinHill.PieceToHint),
		Set.Create(P1Id.DoubleContainersGhost, P2Id.PumpkinTriangle, P3Id.PrayForGoodHarvest, PumpkinHill.PieceToHint),
		Set.Create(P1Id.ThreeFacedGhostPeriod, P2Id.ScarecrowProtectingContainer, P3Id.FlamingEmeralds, PumpkinHill.PieceToHint),
	];

	public override string ToString() => "Pumpkin Hill";

	public override Dictionary<int, string> PieceToHintInstance => PumpkinHill.PieceToHint;
	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(EnemyId.KingOfTheHill), "King of the hill." },
		{ Set.EnumKey(EnemyId.ThreeBrothersTombstone), "Three brothers' tombstone. (enemy)" },
		{ Set.EnumKey(P1Id.UnderTheChimneyNear), "Under the chimney. (upper)" },
		{ Set.EnumKey(P1Id.ItsFloorButAlsoCeilingQuestion), "It's a floor, but it's also a ceiling?" },
		{ Set.EnumKey(P1Id.ScrambleForTheEmeralds), "Scramble for the Emeralds!" },
		{ Set.EnumKey(P1Id.SkullsOnTheRightAndLeft), "Skulls on the right and left." },
		{ Set.EnumKey(P1Id.PathLinedWithRings), "A path lined with rings." },
		{ Set.EnumKey(P1Id.ThreeFacedGhostPeriod), "Three-faced ghost." },
		{ Set.EnumKey(P1Id.SecondSkullFromTheTopLeft), "Second skull from the top, fifth from the bottom. (left)" },
		{ Set.EnumKey(P1Id.UnderTheChimneyFar), "Under the chimney. (lower)" },
		{ Set.EnumKey(P1Id.TurnsButDoesntTurn), "Turns but doesn't turn." },
		{ Set.EnumKey(P1Id.SecondSkullFromTheTopRight), "Second skull from the top, fifth from the bottom. (right)" },
		{ Set.EnumKey(P1Id.TellsTime), "Tells time..." },
		{ Set.EnumKey(P1Id.TombstoneBySomeGrass), "Tombstone by some grass." },
		{ Set.EnumKey(P1Id.ShadyPlace), "Shady place." },
		{ Set.EnumKey(P1Id.ItsAboutToFallOff), "It's about to fall off." },
		{ Set.EnumKey(P1Id.VeryHighUp), "Very high up." },
		{ Set.EnumKey(P1Id.PathOfTheGhostTrain), "Path of the ghost train." },
		{ Set.EnumKey(P1Id.TheSkullMarksTheSpot), "The skull marks the spot." },
		{ Set.EnumKey(P1Id.ThreeFacedGhostQuestion), "A three faced ghost?" },
		{ Set.EnumKey(P1Id.TheTombstoneGuardedByFourSkulls), "The tombstone guarded by four skulls." },
		{ Set.EnumKey(P1Id.ItsAFloorAndAlsoACeilingPeriod), "It's a floor and also a ceiling." },
		{ Set.EnumKey(P1Id.PumpkinFamily), "Pumpkin family." },
		{ Set.EnumKey(P1Id.ThreeSkullBrothers), "Three skull brothers." },
		{ Set.EnumKey(P1Id.LaughingIntoTears), "Laughing into tears." },
		{ Set.EnumKey(P1Id.ThreeFootGap), "A three-foot gap." },
		{ Set.EnumKey(P1Id.ForgottenHutGhost), "Forgotten hut. (Ghost train)" },
		{ Set.EnumKey(P1Id.TwinHuts), "Twin huts." },
		{ Set.EnumKey(P1Id.DoubleContainersGhost), "Double containers. (Ghost train)" },
		{ Set.EnumKey(P1Id.ForgottenHutChurch), "Forgotten hut. (Church)" },
		{ Set.EnumKey(P1Id.ThreeMetalBarrels), "Three metal barrels. (Church)" },
		{ Set.EnumKey(P1Id.DoubleContainersChurch), "Double containers. (Church)" },
		{ Set.EnumKey(P1Id.DoubleContainersPumpkin), "Double containers. (Pumpkin)" },
		{ Set.EnumKey(P1Id.FarmHouse), "A farm house." },
		{ Set.EnumKey(P2Id.SadEyedPumpkinGhost), "Sad-eyed pumpkin. (ghost train)" },
		{ Set.EnumKey(P2Id.UnderTheTracks), "Under the tracks." },
		{ Set.EnumKey(P2Id.TwinSkulls), "Twin skulls." },
		{ Set.EnumKey(P2Id.LaughingPumpkin), "Laughing pumpkin." },
		{ Set.EnumKey(P2Id.ScrambleForTheEmeralds), "Scramble for the Emeralds!" },
		{ Set.EnumKey(P2Id.SadEyedPumpkinPumpkin), "Sad-eyed pumpkin. (pumpkin)" },
		{ Set.EnumKey(P2Id.ItsAboutToFallOff), "It's about to fall off." },
		{ Set.EnumKey(P2Id.TheRocketPath), "The rocket path." },
		{ Set.EnumKey(P2Id.ThreeMetalBarrels), "Three metal barrels." },
		{ Set.EnumKey(P2Id.SleeplessHouse), "Sleepless house." },
		{ Set.EnumKey(P2Id.YouCanSeeItButYouCantTakeIt), "You can see it, but you can't take it..." },
		{ Set.EnumKey(P2Id.ThereIsOnlyOneOnTheCliff), "There is only one on the cliff." },
		{ Set.EnumKey(P2Id.GhostTrainStation), "Ghost train station." },
		{ Set.EnumKey(P2Id.ThePersonYouAreWaitingForArrived), "The person you are waiting for finally arrived." },
		{ Set.EnumKey(P2Id.ScarcrowsHouse), "Scarecrow's house." },
		{ Set.EnumKey(P2Id.ColdIronBars), "Cold iron bars..." },
		{ Set.EnumKey(P2Id.ThreeBrothersTombstoneBuried), "Three brothers' tombstone. (buried)" },
		{ Set.EnumKey(P2Id.UnderTheChimney), "Under the chimney." },
		{ Set.EnumKey(P2Id.TombstoneNearSomeGrass), "A tombstone near some grass." },
		{ Set.EnumKey(P2Id.ChimneyNearSomeGrass), "Chimney near some grass." },
		{ Set.EnumKey(P2Id.SleepWithTheDeadRocket), "Sleep with the dead... (rocket)" },
		{ Set.EnumKey(P2Id.SleepWithTheDeadRings), "Sleep with the dead... (rings)" },
		{ Set.EnumKey(P2Id.SleepWithTheDeadIsland), "Sleep with the dead... (island)" },
		{ Set.EnumKey(P2Id.LonelyTombstone), "Lonely tombstone." },
		{ Set.EnumKey(P2Id.PumpkinsWhoDontGetAlong), "Pumpkins who don't get along." },
		{ Set.EnumKey(P2Id.PlaceYouCantJump), "A place you can't jump..." },
		{ Set.EnumKey(P2Id.PumpkinSnowman), "Pumpkin snowman." },
		{ Set.EnumKey(P2Id.PumpkinFamily), "Pumpkin family." },
		{ Set.EnumKey(P2Id.PumpkinTriangle), "Pumpkin triangle." },
		{ Set.EnumKey(P2Id.UnderAChimney), "Under a chimney." },
		{ Set.EnumKey(P2Id.ScarecrowProtectingContainer), "A scarecrow protecting a container." },
		{ Set.EnumKey(P2Id.SleepBehindAPumpkin), "Sleep behind a pumpkin." },
		{ Set.EnumKey(P3Id.KingOfTheHill), "King of the hill." },
		{ Set.EnumKey(P3Id.SomethingBadGhost), "When you do something bad, this might happen... (Ghost train)" },
		{ Set.EnumKey(P3Id.SadEyedPumpkin), "Sad-eyed pumpkin." },
		{ Set.EnumKey(P3Id.ThreeAgainstThreeStaringAtEachOther), "Three against three staring at each other?" },
		{ Set.EnumKey(P3Id.PlaceYouCanHearTheHorn), "A place you can hear the horn." },
		{ Set.EnumKey(P3Id.SomethingBadChurch), "When you do something bad, this might happen... (Church)" },
		{ Set.EnumKey(P3Id.LostPumpkin), "Lost pumpkin." },
		{ Set.EnumKey(P3Id.ThreeBrothersTombstone), "Three brothers' tombstone." },
		{ Set.EnumKey(P3Id.InTheCenterOfATriangle), "In the center of a triangle." },
		{ Set.EnumKey(P3Id.PlaceWhereYouCanHearTheHornChurch), "A place where you can hear the horn. (Church)" },
		{ Set.EnumKey(P3Id.BeardedMountain), "Bearded mountain...?" },
		{ Set.EnumKey(P3Id.PlaceWhereFlamesCross), "A place where flames cross." },
		{ Set.EnumKey(P3Id.PlaceWhereYouCanHearTheHornPumpkin), "A place where you can hear the horn. (Pumpkin)" },
		{ Set.EnumKey(P3Id.ThreeScarecrowBrothers), "Three scarecrow brothers." },
		{ Set.EnumKey(P3Id.StuffedNose), "Suffering from a stuffed nose?" },
		{ Set.EnumKey(P3Id.TerribleSkullBuried), "Terrible! A skull buried in the rocky wall!" },
		{ Set.EnumKey(P3Id.WanderAroundInACircleDots), "Wander around in a circle..." },
		{ Set.EnumKey(P3Id.StepBackAndWaitNextArrival), "Step back from the platform and wait for the next arrival." },
		{ Set.EnumKey(P3Id.EndlessJourney), "Endless journey." },
		{ Set.EnumKey(P3Id.WanderAroundInACircle), "Wander around in a circle." },
		{ Set.EnumKey(P3Id.OnPatrol), "On patrol?" },
		{ Set.EnumKey(P3Id.AngelsRing), "Angel's ring." },
		{ Set.EnumKey(P3Id.GhostPumpkinNecklace), "Ghost pumpkin's necklace!" },
		{ Set.EnumKey(P3Id.MissilePath), "A missile path." },
		{ Set.EnumKey(P3Id.NoiseUpstairsAndDown), "Noise upstairs and downstairs!" },
		{ Set.EnumKey(P3Id.FlattenedGrass), "Flattened grass." },
		{ Set.EnumKey(P3Id.DangerousMaterial), "On the dangerous material." },
		{ Set.EnumKey(P3Id.YouCanSeeItButYouCantTakeIt), "You can see it, but you can't take it!" },
		{ Set.EnumKey(P3Id.GhostTrainsGuidePost), "Ghost train's guidepost." },
		{ Set.EnumKey(P3Id.PrayForGoodHarvest), "Pray for a good harvest at a holy place." },
		{ Set.EnumKey(P3Id.PumpkinWithCreepySmileLookingAt), "A pumpkin with a creepy smile is looking at...?" },
		{ Set.EnumKey(P3Id.FlamingEmeralds), "Flaming Emeralds." }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string>();

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(PumpkinHill.PieceToHint, PumpkinHill.ImpossiblePieces);

	internal enum EnemyId {
		KingOfTheHill = 0x000A,
		ThreeBrothersTombstone = 0x010A
	}

	internal enum P1Id {
		UnderTheChimneyNear = 0x0001,
		ItsFloorButAlsoCeilingQuestion = 0x0101,
		ScrambleForTheEmeralds = 0x0201,
		SkullsOnTheRightAndLeft = 0x0301,
		PathLinedWithRings = 0x0401,
		ThreeFacedGhostPeriod = 0x0501,
		SecondSkullFromTheTopLeft = 0x0601,
		UnderTheChimneyFar = 0x0701,
		TurnsButDoesntTurn = 0x0801,
		SecondSkullFromTheTopRight = 0x0901,
		TellsTime = 0x0A01,
		TombstoneBySomeGrass = 0x0B01,
		ShadyPlace = 0x0C01,
		ItsAboutToFallOff = 0x0D01,
		VeryHighUp = 0x0E01,
		PathOfTheGhostTrain = 0x0F01,
		TheSkullMarksTheSpot = 0x1001,
		ThreeFacedGhostQuestion = 0x1101,
		TheTombstoneGuardedByFourSkulls = 0x1201,
		ItsAFloorAndAlsoACeilingPeriod = 0x1301,
		PumpkinFamily = 0x1401,
		ThreeSkullBrothers = 0x1501,
		LaughingIntoTears = 0x1601,
		ThreeFootGap = 0x1701,
		ForgottenHutGhost = 0x0003,
		TwinHuts = 0x0103,
		DoubleContainersGhost = 0x0203,
		ForgottenHutChurch = 0x0303,
		ThreeMetalBarrels = 0x0403,
		DoubleContainersChurch = 0x0503,
		DoubleContainersPumpkin = 0x0603,
		FarmHouse = 0x0703
	}
	
	internal enum P2Id {
		SadEyedPumpkinGhost = 0x0000,
		UnderTheTracks = 0x0100,
		TwinSkulls = 0x0200,
		LaughingPumpkin = 0x0300,
		ScrambleForTheEmeralds = 0x0400,
		SadEyedPumpkinPumpkin = 0x0500,
		ItsAboutToFallOff = 0x0600,
		TheRocketPath = 0x0700,
		ThreeMetalBarrels = 0x0002,
		SleeplessHouse = 0x0102,
		YouCanSeeItButYouCantTakeIt = 0x0202,
		ThereIsOnlyOneOnTheCliff = 0x0302,
		GhostTrainStation = 0x0402,
		ThePersonYouAreWaitingForArrived = 0x0502,
		ScarcrowsHouse = 0x0602,
		ColdIronBars = 0x0702,
		ThreeBrothersTombstoneBuried = 0x0005,
		UnderTheChimney = 0x0105,
		TombstoneNearSomeGrass = 0x0205,
		ChimneyNearSomeGrass = 0x0305,
		SleepWithTheDeadRocket = 0x0405,
		SleepWithTheDeadRings = 0x0505,
		SleepWithTheDeadIsland = 0x0605,
		LonelyTombstone = 0x0705,
		PumpkinsWhoDontGetAlong = 0x0805,
		PlaceYouCantJump = 0x0905,
		PumpkinSnowman = 0x0A05,
		PumpkinFamily = 0x0B05,
		PumpkinTriangle = 0x0C05,
		UnderAChimney = 0x0D05,
		ScarecrowProtectingContainer = 0x0E05,
		SleepBehindAPumpkin = 0x0F05
	}

	internal enum P3Id {
		KingOfTheHill = 0x0004,
		SomethingBadGhost = 0x0104,
		SadEyedPumpkin = 0x0204,
		ThreeAgainstThreeStaringAtEachOther = 0x0304,
		PlaceYouCanHearTheHorn = 0x0404,
		SomethingBadChurch = 0x0504,
		LostPumpkin = 0x0604,
		ThreeBrothersTombstone = 0x0704,
		InTheCenterOfATriangle = 0x0804,
		PlaceWhereYouCanHearTheHornChurch = 0x0904,
		BeardedMountain = 0x0A04,
		PlaceWhereFlamesCross = 0x0B04,
		PlaceWhereYouCanHearTheHornPumpkin = 0x0C04,
		ThreeScarecrowBrothers = 0x0D04,
		StuffedNose = 0x0E04,
		TerribleSkullBuried = 0x0F04,
		WanderAroundInACircleDots = 0x0007,
		StepBackAndWaitNextArrival = 0x0107,
		EndlessJourney = 0x0207,
		WanderAroundInACircle = 0x0307,
		OnPatrol = 0x0407,
		AngelsRing = 0x0507,
		GhostPumpkinNecklace = 0x0607,
		MissilePath = 0x0707,
		NoiseUpstairsAndDown = 0x0008,
		FlattenedGrass = 0x0108,
		DangerousMaterial = 0x0208,
		YouCanSeeItButYouCantTakeIt = 0x0308,
		GhostTrainsGuidePost = 0x0408,
		PrayForGoodHarvest = 0x0508,
		PumpkinWithCreepySmileLookingAt = 0x0608,
		FlamingEmeralds = 0x0708
	}
}
