namespace sa2_hunting_teacher.Knuckles;

public class WildCanyon(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.WildCanyon;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.InsideStatueStorageAreaLeft, P2Id.RedGateChest, P3Id.TheBeginningRoom, WildCanyon.PieceToHint),
		Set.Create(EnemyId.NearSixPillarsMetalBoxes, P2Id.SandyPathLeadsStoneStatueHead, P3Id.WildCanyonTrack, WildCanyon.PieceToHint),
		Set.Create(EnemyId.NearSixPillarsScaryEyes, EnemyId.SandyPathRhino, P3Id.InFrontOfMountainWithGreenAndRedStripes, WildCanyon.PieceToHint),
		Set.Create(P1Id.InFrontDoubleContainersLeft, P2Id.BirdBoxMiddle, P3Id.OverTheTiltedPillar, WildCanyon.PieceToHint),
		Set.Create(P1Id.TreasureOfFourStoneStatues, EnemyId.SandyPathNearHawk, P3Id.OnTheScaryEyesWildCanyonTrack, WildCanyon.PieceToHint),
		Set.Create(P1Id.BetweenTwinStars, P2Id.BirdBoxLeft, P3Id.BetweenTheRedPillarsUnderWeight, WildCanyon.PieceToHint),
		Set.Create(P1Id.PlacePointedTwoPriests, P2Id.RedGateBox, P3Id.InFrontOfMountainRedAndGreenStripesContainers, WildCanyon.PieceToHint),
		Set.Create(P1Id.DoubleContainersLeft, P2Id.SwirlingContainer, P3Id.BetweenTheRedPillarsBehindWeight, WildCanyon.PieceToHint),
		Set.Create(P1Id.DoubleContainersRight, P2Id.ArmoredCarpoolCorner, P3Id.WhereTheWindBlows, WildCanyon.PieceToHint),
		Set.Create(P1Id.InFrontDoubleContainersRight, EnemyId.SuspendedCeilingEnemy, P3Id.InAStormZoneMiddle, WildCanyon.PieceToHint),
		Set.Create(P1Id.BirdBoxRedPing, P2Id.TerraceWithTwoLegsUnder, P3Id.Sandpit, WildCanyon.PieceToHint),
		Set.Create(EnemyId.StoneStatueQuartetHeadSide, P2Id.BehindAFaceMiddle, P3Id.ByATallPillar, WildCanyon.PieceToHint),
		Set.Create(P1Id.ByAWindJumpBoard, EnemyId.SandyPathFarHawk, P3Id.TheAltarWithSixPillars, WildCanyon.PieceToHint),
		Set.Create(EnemyId.NearSixPillarsRedCircle, P2Id.FourSwirlingEyes, P3Id.InFrontOfMountainRedAndGreenStripesChest, WildCanyon.PieceToHint),
		Set.Create(P1Id.OverTheHead, P2Id.BirdBoxInTheShade, P3Id.WhereWindIsGenerated, WildCanyon.PieceToHint),
		Set.Create(P1Id.HeadOfThe4thStoneStatue, P2Id.BehindAFaceRight, P3Id.OnARedCircle, WildCanyon.PieceToHint),
		Set.Create(P1Id.StatueWithScaryEyes, EnemyId.NearSixPillarsMetalBoxes, P3Id.OnSandyPathToAStatueHead, WildCanyon.PieceToHint),
		Set.Create(P1Id.SuspendedCeilingExposed, P2Id.SwirlingArrow, P3Id.InTheCenterOf8thPillar, WildCanyon.PieceToHint),
		Set.Create(P1Id.TopOfTenFingers, P2Id.InsideStatueStorageArea, P3Id.BetweenTwoStoneStatues, WildCanyon.PieceToHint),
		Set.Create(P1Id.SwirlingContainer, P2Id.FourWhirlingEyes, P3Id.OnLapOfWallPainting, WildCanyon.PieceToHint),
		Set.Create(P1Id.WildCanyonTrack, P2Id.BottomOfAPillar, P3Id.Swirling, WildCanyon.PieceToHint),
		Set.Create(P1Id.BottomOfAPillar, P2Id.AtTheFootOfAPillar, P3Id.GoldenPath, WildCanyon.PieceToHint),
		Set.Create(P1Id.BottomOfHugeWallPainting, EnemyId.StoneStatueQuartetLonelySide, P3Id.BetweenTwoStoneStatues, WildCanyon.PieceToHint),
		Set.Create(P1Id.OnSideBirdChestUnderFourFeathers, P2Id.OnARailwayBottomRight, P3Id.FourWhirlingEyesHead, WildCanyon.PieceToHint),
		Set.Create(P1Id.OnThePillar, P2Id.SwirlPyramid, P3Id.InAStormZoneLeft, WildCanyon.PieceToHint),
		Set.Create(EnemyId.StoneStatueQuartetLonelySide, P2Id.UnderWingsOfTwoBirds, P3Id.InAStormZoneBelow, WildCanyon.PieceToHint),
		Set.Create(P1Id.InFrontBirdChestUnderFourFeathers, P2Id.ArmoredCarpoolCenter, P3Id.ArrowPointingToTheRight, WildCanyon.PieceToHint),
		Set.Create(EnemyId.SandyPathNearHawk, P2Id.WildCanyonTrackCorner, P3Id.PillarWithoutTreasure, WildCanyon.PieceToHint),
		Set.Create(P1Id.SpiralTile, P2Id.WhereTheWindBlows, P3Id.TerraceWithTwoLegs, WildCanyon.PieceToHint),
		Set.Create(EnemyId.NearSixPillarsRailways, P2Id.WildCanyonTrackCenter, P3Id.FourWhirlingEyesLonely, WildCanyon.PieceToHint),
		Set.Create(P1Id.GoldenCircleOnRedCircle, P2Id.OnARailwayUpper, P3Id.FourWhirlingEyesHead, WildCanyon.PieceToHint),
		Set.Create(P1Id.AltarWithSixPillars, P2Id.TerraceWithTwoLegsBehind, P3Id.SandyPathToTheHeadOfStoneStatue, WildCanyon.PieceToHint),
		Set.Create(P1Id.Parakeet, P2Id.NearAChair, P3Id.GoldenPath, WildCanyon.PieceToHint),
		Set.Create(P1Id.HesHoldingABox, P2Id.UnderTheElbowHead, P3Id.Swirling, WildCanyon.PieceToHint),
		Set.Create(P1Id.BetweenRedAndGreenStripedPillars, EnemyId.NearSixPillarsRedCircle, P3Id.OrbitingAboveFace, WildCanyon.PieceToHint),
		Set.Create(EnemyId.SandyPathRhino, EnemyId.NearSixPillarsRailways, P3Id.RedAndGreenStripes, WildCanyon.PieceToHint),
		Set.Create(P1Id.InsideStatueStorageAreaRight, P2Id.OnARailwayBottomLeft, P3Id.SandyPathToTheHeadOfStoneStatue, WildCanyon.PieceToHint),
		Set.Create(P1Id.BottomSwirlTilePyramid, EnemyId.NearSixPillarsScaryEyes, P3Id.SandyPathToTheHeadOfStoneStatue, WildCanyon.PieceToHint),
		Set.Create(P1Id.BetweenFourBirds, EnemyId.StoneStatueQuartetHeadSide, P3Id.SandyPathToTheHeadOfStoneStatue, WildCanyon.PieceToHint),
		Set.Create(EnemyId.SandyPathFarHawk, P2Id.BirdBoxMiddle, P3Id.TheAltarWithSixPillars, WildCanyon.PieceToHint),
		Set.Create(P1Id.APairOfEarrings, P2Id.BirdBoxUpper, P3Id.BetweenTwoStoneStatues, WildCanyon.PieceToHint),
		Set.Create(EnemyId.SuspendedCeilingEnemy, P2Id.WhereTheWindBlows, P3Id.InTheCenterOf8thPillar, WildCanyon.PieceToHint),
	];

	public override string ToString() => "Wild Canyon";

	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string>{
		{ Set.EnumKey(EnemyId.SuspendedCeilingEnemy), "A suspended ceiling. (enemy)" },
		{ Set.EnumKey(EnemyId.SandyPathRhino), "On a sandy path to a stone statue head. (Rhino)" },
		{ Set.EnumKey(EnemyId.SandyPathNearHawk), "On a sandy path to a stone statue head. (near Hawk)" },
		{ Set.EnumKey(EnemyId.SandyPathFarHawk), "On a sandy path to a stone statue head. (far Hawk)" },
		{ Set.EnumKey(EnemyId.NearSixPillarsRedCircle), "Near the six pillars. (red circle)" },
		{ Set.EnumKey(EnemyId.NearSixPillarsMetalBoxes), "Near the six pillars. (metal boxes)" },
		{ Set.EnumKey(EnemyId.NearSixPillarsScaryEyes), "Near the six pillars. (scary eyes)" },
		{ Set.EnumKey(EnemyId.NearSixPillarsRailways), "Near the six pillars. (railways)" },
		{ Set.EnumKey(EnemyId.StoneStatueQuartetHeadSide), "Stone statue quartet. (head side)" },
		{ Set.EnumKey(EnemyId.StoneStatueQuartetLonelySide), "Stone statue quartet. (lonely side)" },
		{ Set.EnumKey(P1Id.InFrontDoubleContainersLeft), "In front of the double containers. (left)" },
		{ Set.EnumKey(P1Id.InFrontDoubleContainersRight), "In front of the double containers. (right)" },
		{ Set.EnumKey(P1Id.InFrontBirdChestUnderFourFeathers), "In front of a bird chest under four feathers." },
		{ Set.EnumKey(P1Id.OnSideBirdChestUnderFourFeathers), "On the side of a bird chest under four feathers." },
		{ Set.EnumKey(P1Id.SuspendedCeilingExposed), "A suspended ceiling. (exposed)" },
		{ Set.EnumKey(P1Id.GoldenCircleOnRedCircle), "A golden circle on a red circle." },
		{ Set.EnumKey(P1Id.HesHoldingABox), "He's holding a box." },
		{ Set.EnumKey(P1Id.Parakeet), "A parakeet on the left shoulder." },
		{ Set.EnumKey(P1Id.BottomSwirlTilePyramid), "At the bottom of a swirl tile pyramid." },
		{ Set.EnumKey(P1Id.ByAWindJumpBoard), "By a wind jump board." },
		{ Set.EnumKey(P1Id.PlacePointedTwoPriests), "The place pointed out by two priests." },
		{ Set.EnumKey(P1Id.HeadOfThe4thStoneStatue), "The head of the 4th stone statue." },
		{ Set.EnumKey(P1Id.BetweenTwinStars), "Between the twin stars." },
		{ Set.EnumKey(P1Id.APairOfEarrings), "A pair of earrings." },
		{ Set.EnumKey(P1Id.OnThePillar), "On the pillar." },
		{ Set.EnumKey(P1Id.BottomOfAPillar), "At the bottom of a pillar." },
		{ Set.EnumKey(P1Id.SpiralTile), "On the spiral tile." },
		{ Set.EnumKey(P1Id.OverTheHead), "Over the head." },
		{ Set.EnumKey(P1Id.AltarWithSixPillars), "The altar with six pillars." },
		{ Set.EnumKey(P1Id.BetweenFourBirds), "Between four birds." },
		{ Set.EnumKey(P1Id.BetweenRedAndGreenStripedPillars), "Between the red and green striped pillars." },
		{ Set.EnumKey(P1Id.WildCanyonTrack), "\"Wild Canyon Track.\"" },
		{ Set.EnumKey(P1Id.BottomOfHugeWallPainting), "At the bottom of a huge wall painting." },
		{ Set.EnumKey(P1Id.TopOfTenFingers), "On the top of ten fingers." },
		{ Set.EnumKey(P1Id.DoubleContainersLeft), "Double containers. (left)" },
		{ Set.EnumKey(P1Id.DoubleContainersRight), "Double containers. (right)" },
		{ Set.EnumKey(P1Id.InsideStatueStorageAreaRight), "Inside a statue storage area. (right)" },
		{ Set.EnumKey(P1Id.StatueWithScaryEyes), "A statue with scary eyes." },
		{ Set.EnumKey(P1Id.InsideStatueStorageAreaLeft), "Inside a statue storage area. (left)" },
		{ Set.EnumKey(P1Id.TreasureOfFourStoneStatues), "A treasure of four stone statues." },
		{ Set.EnumKey(P1Id.BirdBoxRedPing), "A bird box." },
		{ Set.EnumKey(P1Id.SwirlingContainer), "A swirling container." },
		{ Set.EnumKey(P2Id.ArmoredCarpoolCenter), "Armored carpool. (center)" },
		{ Set.EnumKey(P2Id.ArmoredCarpoolCorner), "Armored carpool. (corner)" },
		{ Set.EnumKey(P2Id.AtTheFootOfAPillar), "At the foot of a pillar." },
		{ Set.EnumKey(P2Id.SwirlPyramid), "A swirl pyramid." },
		{ Set.EnumKey(P2Id.TerraceWithTwoLegsUnder), "A terrace with two legs. (under weight)" },
		{ Set.EnumKey(P2Id.TerraceWithTwoLegsBehind), "A terrace with two legs. (behind weight)" },
		{ Set.EnumKey(P2Id.NearAChair), "Near a chair." },
		{ Set.EnumKey(P2Id.SandyPathLeadsStoneStatueHead), "On a sandy path that leads to a stone statue head." },
		{ Set.EnumKey(P2Id.FourWhirlingEyes), "Four whirling eyes." },
		{ Set.EnumKey(P2Id.FourSwirlingEyes), "Four swirling eyes." },
		{ Set.EnumKey(P2Id.InsideStatueStorageArea), "Inside a statue storage area." },
		{ Set.EnumKey(P2Id.BirdBoxInTheShade), "A bird box in the shade." },
		{ Set.EnumKey(P2Id.BottomOfAPillar), "At the bottom of a pillar." },
		{ Set.EnumKey(P2Id.BirdBoxUpper), "A bird box. (upper)" },
		// { Set.EnumKey(P2Id.UnderTheElbowLonelyImpossible), "Under the elbow. (lonely side)" },
		{ Set.EnumKey(P2Id.UnderWingsOfTwoBirds), "Under the wings of two birds." },
		{ Set.EnumKey(P2Id.RedGateChest), "A red gate. (chest)" },
		{ Set.EnumKey(P2Id.RedGateBox), "A red gate. (box)" },
		{ Set.EnumKey(P2Id.BirdBoxMiddle), "A bird box. (middle)" },
		{ Set.EnumKey(P2Id.WhereTheWindBlows), "Where the wind blows." },
		{ Set.EnumKey(P2Id.SwirlingContainer), "A swirling container." },
		{ Set.EnumKey(P2Id.BirdBoxLeft), "A bird box. (left)" },
		{ Set.EnumKey(P2Id.WildCanyonTrackCorner), "\"Wild Canyon Track.\" (corner)" },
		{ Set.EnumKey(P2Id.UnderTheElbowHead), "Under the elbow. (head side)" },
		{ Set.EnumKey(P2Id.BehindAFaceRight), "Behind a face. (right)" },
		{ Set.EnumKey(P2Id.BehindAFaceMiddle), "Behind a face. (middle)" },
		{ Set.EnumKey(P2Id.OnARailwayUpper), "On a railway. (upper)" },
		{ Set.EnumKey(P2Id.OnARailwayBottomRight), "On a railway. (bottom right)" },
		{ Set.EnumKey(P2Id.OnARailwayBottomLeft), "On a railway. (bottom left)" },
		{ Set.EnumKey(P2Id.SwirlingArrow), "A swirling arrow." },
		{ Set.EnumKey(P2Id.WildCanyonTrackCenter), "\"Wild Canyon Track.\" (center)" },
		{ Set.EnumKey(P3Id.SandyPathToTheHeadOfStoneStatue), "A sandy path to the head of a stone statue." },
		{ Set.EnumKey(P3Id.BetweenTheRedPillarsUnderWeight), "Between the red pillars. (under weight)" },
		{ Set.EnumKey(P3Id.Swirling), "Swirling." },
		{ Set.EnumKey(P3Id.OnARedCircle), "On a red circle." },
		{ Set.EnumKey(P3Id.OnTheScaryEyesWildCanyonTrack), "On the scary eyes in the \"Wild Canyon Track.\"" },
		{ Set.EnumKey(P3Id.PillarWithoutTreasure), "A pillar without a treasure." },
		{ Set.EnumKey(P3Id.OnLapOfWallPainting), "On the lap of a wall painting." },
		{ Set.EnumKey(P3Id.ArrowPointingToTheRight), "The arrow pointing to the right." },
		{ Set.EnumKey(P3Id.FourWhirlingEyesHead), "Four whirling eyes. (head side)" },
		{ Set.EnumKey(P3Id.FourWhirlingEyesLonely), "Four whirling eyes. (lonely side)" },
		{ Set.EnumKey(P3Id.InFrontOfMountainWithGreenAndRedStripes), "In front of a mountain with green and red stripes." },
		{ Set.EnumKey(P3Id.WhereWindIsGenerated), "Where wind is generated." },
		{ Set.EnumKey(P3Id.ByATallPillar), "By a tall pillar." },
		{ Set.EnumKey(P3Id.InTheCenterOf8thPillar), "In the center of the 8th pillar." },
		{ Set.EnumKey(P3Id.BetweenTheRedPillarsBehindWeight), "Between the red pillars. (behind weight)" },
		{ Set.EnumKey(P3Id.OverTheTiltedPillar), "Over the tilted pillar." },
		{ Set.EnumKey(P3Id.OnSandyPathToAStatueHead), "On a sandy path to a statue head." },
		{ Set.EnumKey(P3Id.OrbitingAboveFace), "Orbiting above the face." },
		{ Set.EnumKey(P3Id.WildCanyonTrack), "\"Wild Canyon Track.\"" },
		{ Set.EnumKey(P3Id.WhereTheWindBlows), "Where the wind blows." },
		{ Set.EnumKey(P3Id.Sandpit), "A sandpit." },
		{ Set.EnumKey(P3Id.RedAndGreenStripes), "Red and green stripes." },
		{ Set.EnumKey(P3Id.TheAltarWithSixPillars), "The altar with six pillars." },
		{ Set.EnumKey(P3Id.BetweenTwoStoneStatues), "Between two stone statues." },
		{ Set.EnumKey(P3Id.InFrontOfMountainRedAndGreenStripesChest), "In front of a mountain with red and green stripes. (chest side)" },
		{ Set.EnumKey(P3Id.InFrontOfMountainRedAndGreenStripesContainers), "In front of a mountain with red and green stripes. (containers side)" },
		{ Set.EnumKey(P3Id.InAStormZoneMiddle), "In a storm zone. (middle)" },
		{ Set.EnumKey(P3Id.InAStormZoneLeft), "In a storm zone. (left)" },
		{ Set.EnumKey(P3Id.TerraceWithTwoLegs), "A terrace with two legs." },
		{ Set.EnumKey(P3Id.GoldenPath), "The golden path." },
		{ Set.EnumKey(P3Id.InAStormZoneBelow), "In a storm zone. (below)" },
		{ Set.EnumKey(P3Id.TheBeginningRoom), "The beginning room." }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(P2Id.UnderTheElbowLonelyImpossible), "Under the elbow. (lonely side)" }
	};

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(WildCanyon.PieceToHint, WildCanyon.ImpossiblePieces);

	internal enum EnemyId {
		SuspendedCeilingEnemy = 0x000A,
		SandyPathRhino = 0x010A,
		SandyPathNearHawk = 0x020A,
		SandyPathFarHawk = 0x030A,
		NearSixPillarsRedCircle = 0x040A,
		NearSixPillarsMetalBoxes = 0x050A,
		NearSixPillarsScaryEyes = 0x060A,
		NearSixPillarsRailways = 0x070A,
		StoneStatueQuartetHeadSide = 0x080A,
		StoneStatueQuartetLonelySide = 0x090A
	}

	internal enum P1Id {
		InFrontDoubleContainersLeft = 0x0001,
		InFrontDoubleContainersRight = 0x0101,
		InFrontBirdChestUnderFourFeathers = 0x0201,
		OnSideBirdChestUnderFourFeathers = 0x0301,
		SuspendedCeilingExposed = 0x0401,
		GoldenCircleOnRedCircle = 0x0501,
		HesHoldingABox = 0x0601,
		Parakeet = 0x0701,
		BottomSwirlTilePyramid = 0x0801,
		ByAWindJumpBoard = 0x0901,
		PlacePointedTwoPriests = 0x0A01,
		HeadOfThe4thStoneStatue = 0x0B01,
		BetweenTwinStars = 0x0C01,
		APairOfEarrings = 0x0D01,
		OnThePillar = 0x0E01,
		BottomOfAPillar = 0x0F01,
		SpiralTile = 0x1001,
		OverTheHead = 0x1101,
		AltarWithSixPillars = 0x1201,
		BetweenFourBirds = 0x1301,
		BetweenRedAndGreenStripedPillars = 0x1401,
		WildCanyonTrack = 0x1501,
		BottomOfHugeWallPainting = 0x1601,
		TopOfTenFingers = 0x1701,
		DoubleContainersLeft = 0x0003,
		DoubleContainersRight = 0x0103,
		InsideStatueStorageAreaRight = 0x0203,
		StatueWithScaryEyes = 0x0303,
		InsideStatueStorageAreaLeft = 0x0403,
		TreasureOfFourStoneStatues = 0x0503,
		BirdBoxRedPing = 0x0603,
		SwirlingContainer = 0x0703
	}

	internal enum P2Id {
		ArmoredCarpoolCenter = 0x0000,
		ArmoredCarpoolCorner = 0x0100,
		AtTheFootOfAPillar = 0x0200,
		SwirlPyramid = 0x0300,
		TerraceWithTwoLegsUnder = 0x0400,
		TerraceWithTwoLegsBehind = 0x0500,
		NearAChair = 0x0600,
		SandyPathLeadsStoneStatueHead = 0x0700,
		FourWhirlingEyes = 0x0002,
		FourSwirlingEyes = 0x0102,
		InsideStatueStorageArea = 0x0202,
		BirdBoxInTheShade = 0x0402,
		BottomOfAPillar = 0x0502,
		BirdBoxUpper = 0x0602,
		UnderTheElbowLonelyImpossible = 0x0702, // Impossible Piece
		UnderWingsOfTwoBirds = 0x0005,
		RedGateChest = 0x0105,
		RedGateBox = 0x0205,
		BirdBoxMiddle = 0x0305,
		WhereTheWindBlows = 0x0405,
		SwirlingContainer = 0x0505,
		BirdBoxLeft = 0x0605,
		WildCanyonTrackCorner = 0x0705,
		UnderTheElbowHead = 0x0805,
		BehindAFaceRight = 0x0905,
		BehindAFaceMiddle = 0x0A05,
		OnARailwayUpper = 0x0B05,
		OnARailwayBottomRight = 0x0C05,
		OnARailwayBottomLeft = 0x0D05,
		SwirlingArrow = 0x0E05,
		WildCanyonTrackCenter = 0x0F05
	}

	internal enum P3Id {
		SandyPathToTheHeadOfStoneStatue = 0x0004,
		BetweenTheRedPillarsUnderWeight = 0x0104,
		Swirling = 0x0204,
		OnARedCircle = 0x0304,
		OnTheScaryEyesWildCanyonTrack = 0x0404,
		PillarWithoutTreasure = 0x0504,
		OnLapOfWallPainting = 0x0604,
		ArrowPointingToTheRight = 0x0704,
		FourWhirlingEyesHead = 0x0804,
		FourWhirlingEyesLonely = 0x0904,
		InFrontOfMountainWithGreenAndRedStripes = 0x0A04,
		WhereWindIsGenerated = 0x0B04,
		ByATallPillar = 0x0C04,
		InTheCenterOf8thPillar = 0x0D04,
		BetweenTheRedPillarsBehindWeight = 0x0E04,
		OverTheTiltedPillar = 0x0F04,
		OnSandyPathToAStatueHead = 0x0007,
		OrbitingAboveFace = 0x0107,
		WildCanyonTrack = 0x0207,
		WhereTheWindBlows = 0x0307,
		Sandpit = 0x0407,
		RedAndGreenStripes = 0x0507,
		TheAltarWithSixPillars = 0x0607,
		BetweenTwoStoneStatues = 0x0707,
		InFrontOfMountainRedAndGreenStripesChest = 0x0008,
		InFrontOfMountainRedAndGreenStripesContainers = 0x0108,
		InAStormZoneMiddle = 0x0208,
		InAStormZoneLeft = 0x0308,
		TerraceWithTwoLegs = 0x0408,
		GoldenPath = 0x0508,
		InAStormZoneBelow = 0x0608,
		TheBeginningRoom = 0x0708
	}
}
