namespace sa2_hunting_teacher.Rouge;

public class DryLagoon(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.DryLagoon;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.PlantsInTheShade, P2Id.OnTheHeadLeft, P3Id.PlantsInTheShade, DryLagoon.PieceToHint),
		Set.Create(P1Id.StoneStatuesTreasure, P2Id.GunsMiniStorageAreaGuarded, P3Id.BetweenTheSunsFacingEachOtherNear, DryLagoon.PieceToHint),
		Set.Create(P1Id.ByTheFarAwayPond, P2Id.BlueAndWhiteV, P3Id.ButterflysTreasure, DryLagoon.PieceToHint),
		Set.Create(P1Id.ThePoolInFrontOfWall, P2Id.BehindTheRubble, P3Id.GoUpAndDownStairs, DryLagoon.PieceToHint),
		Set.Create(P1Id.GunsStorageAreaRight, P2Id.BlueBox, P3Id.FloatingWithButterflies, DryLagoon.PieceToHint),
		Set.Create(P1Id.UnderTheStarGunsStorageArea, P2Id.BehindThePillarPlants, P3Id.UnderTurtlesFace, DryLagoon.PieceToHint),
		Set.Create(EnemyId.ProtectorOfThePond, P2Id.ACoconutBigOasis, P3Id.OnTheBiggestTurtleShellStatic, DryLagoon.PieceToHint),
		Set.Create(P1Id.OnAHexagonPillarHeads, P2Id.JarStoragePlace, P3Id.TurtlesTunnelStatic, DryLagoon.PieceToHint),
		Set.Create(P1Id.BlueAndWhiteV, P2Id.EnchantedPillar, P3Id.TurtlesTunnelMoving, DryLagoon.PieceToHint),
		Set.Create(P1Id.UnderwaterBalconyApartments, P2Id.RazorPlant, P3Id.MovingBetweenBigAndSmallPillars, DryLagoon.PieceToHint),
		Set.Create(P1Id.GunsStorageAreaLeft, P2Id.InTheCornerOfRoomWithHeiroglyphics, P3Id.UnderAChinLeft, DryLagoon.PieceToHint),
		Set.Create(P1Id.ByTheFootOfAShell, P2Id.ACoconutSmallOasis, P3Id.OnTopOfAPalmTree, DryLagoon.PieceToHint),
		Set.Create(P1Id.UnderwaterBalconyTurtle, P2Id.GunsJar, P3Id.BeneathApartments, DryLagoon.PieceToHint),
		Set.Create(P1Id.BlueStripedHeadBigOasis, EnemyId.GunsGuardForTheStorageArea, P3Id.CircleAroundTheTiltedPillar, DryLagoon.PieceToHint),
		Set.Create(P1Id.ALotOfSquareFacesFar, EnemyId.ProtectorOfTheJarRight, P3Id.BetweenTheSunsFacingEachOtherFar, DryLagoon.PieceToHint),
		Set.Create(P1Id.HugeScreenJars, P2Id.BlueAndWhiteStripedPillar, P3Id.FloatingWithButterflies, DryLagoon.PieceToHint),
		Set.Create(P1Id.BlueStripedHeadSmallOasis, P2Id.BehindTheWaterPlant, P3Id.OnTheTiltedPillar, DryLagoon.PieceToHint),
		Set.Create(P1Id.InBetweenMiniPillars, P2Id.OnTheHeadMiddle, P3Id.BullsEye, DryLagoon.PieceToHint),
		Set.Create(P1Id.Offering, P2Id.GunsMiniStorageAreaUnguarded, P3Id.OnTheBiggestTurtleShellMoving, DryLagoon.PieceToHint),
		Set.Create(P1Id.BlueBoxSurroundedByFourStakesLeftBox, P2Id.TearsOfGiant, P3Id.BullsEye, DryLagoon.PieceToHint),
		Set.Create(P1Id.OnTheLedgeWithThreeRedCirclesOutJar, P2Id.OnTheHeadMiddle, P3Id.RedFlowerInTheWaterFarPond, DryLagoon.PieceToHint),
		Set.Create(P1Id.ForgottenLittleBoat, P2Id.GunsMiniStorageAreaGuarded, P3Id.OasisJailPeriod, DryLagoon.PieceToHint),
		Set.Create(P1Id.BlueBoxSurroundedByFourStakesRightBox, P2Id.ACoconutPeriod, P3Id.EnchantedPillar, DryLagoon.PieceToHint),
		Set.Create(P1Id.OutsideAJailCell, P2Id.ACoconutPeriod, P3Id.RedFlowerInTheWaterFarPond, DryLagoon.PieceToHint),
		Set.Create(P1Id.RedFlowersAndRedPillar, P2Id.SecondFloorApartments, P3Id.PlaceWhereWaterComesFrom, DryLagoon.PieceToHint),
		Set.Create(P1Id.ALotOfSquareFacesClose, P2Id.StoneStatuesTreasure, P3Id.CircleAroundTheSmallSun, DryLagoon.PieceToHint),
		Set.Create(EnemyId.GunsGuardOfTheStorageArea, P2Id.BehindThePillarPlants, P3Id.UnderTurtlesFace, DryLagoon.PieceToHint),
		Set.Create(P1Id.GreenPool, P2Id.StoneMonumentOfTheSun, P3Id.BeneathApartments, DryLagoon.PieceToHint),
		Set.Create(P1Id.HugeScreenJars, P2Id.TurtlesPathFar, P3Id.CircleAroundTheSmallSun, DryLagoon.PieceToHint),
		Set.Create(P1Id.RedFlowersAndRedPillar, P2Id.JarSurroundedByThreeStakes, P3Id.RedFlowerInTheWaterJail, DryLagoon.PieceToHint),
		Set.Create(P1Id.OnAHexagonPillarApartment, P2Id.StoneStatuesTreasure, P3Id.UnderTurtlesFace, DryLagoon.PieceToHint),
		Set.Create(P1Id.HugeScreenPool, P2Id.UnderneathPlatformWithFourStakes, P3Id.DryLagoonThermometer, DryLagoon.PieceToHint),
		Set.Create(P1Id.SecondFloorRooftopApartments, P2Id.GunsJar, P3Id.OasisJailPeriod, DryLagoon.PieceToHint),
		Set.Create(P1Id.GreenPool, P2Id.BlueAndWhiteStripedTunnelSubmerged, P3Id.ButterflysTreasure, DryLagoon.PieceToHint),
		Set.Create(P1Id.FirstFloorApartments, P2Id.OnTheHeadLeft, P3Id.InFrontOfWhiteBricks, DryLagoon.PieceToHint),
		Set.Create(P1Id.HugeScreenJars, P2Id.EmeraldLeaf, P3Id.EnchantedPillar, DryLagoon.PieceToHint),
		Set.Create(P1Id.GreenPool, P2Id.BlueAndWhiteStripedPillar, P3Id.OnTheBiggestTurtleShellMoving, DryLagoon.PieceToHint),
		Set.Create(EnemyId.ProtectorOfTheJarLeft, P2Id.TwoHugePillars, P3Id.PlaceWhereWaterComesFrom, DryLagoon.PieceToHint),
		Set.Create(P1Id.GreenPool, P2Id.TurtlesPathClose, P3Id.OnTopOfAPalmTree, DryLagoon.PieceToHint),
		Set.Create(P1Id.SecondFloorRooftopApartments, P2Id.OnTheHeadMiddle, P3Id.OasisJail, DryLagoon.PieceToHint),
		Set.Create(P1Id.OnAHexagonPillarHeads, P2Id.ByTheGiantsChair, P3Id.RedFlowerInTheWaterFarPond, DryLagoon.PieceToHint),
		Set.Create(P1Id.OnTheLedgeWithThreeRedCirclesInJar, P2Id.ACoconutSmallOasis, P3Id.UnderAChinRight, DryLagoon.PieceToHint),
		Set.Create(P1Id.SecondFloorApartments, P2Id.BlueAndWhiteStripedTunnelCorner, P3Id.FishFood, DryLagoon.PieceToHint),
	];

	public override string ToString() => "Dry Lagoon";

	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string>{
		{ Set.EnumKey(EnemyId.GunsGuardForTheStorageArea), "GUN's guard for the storage area." },
		{ Set.EnumKey(EnemyId.ProtectorOfThePond), "Protector of the pond." },
		{ Set.EnumKey(EnemyId.ProtectorOfTheJarLeft), "Protector of the jar. (left from spawn)" },
		{ Set.EnumKey(EnemyId.ProtectorOfTheJarRight), "Protector of the jar. (right from spawn)" },
		{ Set.EnumKey(EnemyId.GunsGuardOfTheStorageArea), "GUN's guard of the storage area." },
		{ Set.EnumKey(P1Id.OnTheLedgeWithThreeRedCirclesOutJar), "On the ledge with three red circles. (out of jar)" },
		{ Set.EnumKey(P1Id.Offering), "Offering." },
		{ Set.EnumKey(P1Id.OnAHexagonPillarApartment), "On a hexagon pillar. (apartment side)" },
		{ Set.EnumKey(P1Id.OnAHexagonPillarHeads), "On a hexagon pillar. (heads side)" },
		{ Set.EnumKey(P1Id.InBetweenMiniPillars), "In between the mini pillars." },
		{ Set.EnumKey(P1Id.RedFlowersAndRedPillar), "Red flowers and red pillar." },
		{ Set.EnumKey(P1Id.ForgottenLittleBoat), "Forgotten little boat." },
		{ Set.EnumKey(P1Id.ByTheFarAwayPond), "By the far away pond." },
		{ Set.EnumKey(P1Id.ByTheFootOfAShell), "By the foot of a shell." },
		{ Set.EnumKey(P1Id.OutsideAJailCell), "Outside a jail cell." },
		{ Set.EnumKey(P1Id.UnderwaterBalconyApartments), "Underwater balcony. (apartments side)" },
		{ Set.EnumKey(P1Id.UnderwaterBalconyTurtle), "Underwater balcony. (turtle)" },
		{ Set.EnumKey(P1Id.ALotOfSquareFacesClose), "A lot of square faces. (close)" },
		{ Set.EnumKey(P1Id.ALotOfSquareFacesFar), "A lot of square faces. (far)" },
		{ Set.EnumKey(P1Id.BlueAndWhiteV), "Blue and white \"V\"." },
		{ Set.EnumKey(P1Id.StoneStatuesTreasure), "Stone statue's treasure." },
		{ Set.EnumKey(P1Id.BlueStripedHeadBigOasis), "Blue striped head. (big oasis)" },
		{ Set.EnumKey(P1Id.BlueStripedHeadSmallOasis), "Blue striped head. (small oasis)" },
		{ Set.EnumKey(P1Id.GreenPool), "Green pool." },
		{ Set.EnumKey(P1Id.ThePoolInFrontOfWall), "The pool in front of the wall." },
		{ Set.EnumKey(P1Id.GunsStorageAreaRight), "GUN's storage area. (right box)" },
		{ Set.EnumKey(P1Id.GunsStorageAreaLeft), "GUN's storage area. (left box)" },
		{ Set.EnumKey(P1Id.HugeScreenJars), "Huge screen. (jars)" },
		{ Set.EnumKey(P1Id.HugeScreenPool), "Huge screen. (pool)" },
		{ Set.EnumKey(P1Id.OnTheLedgeWithThreeRedCirclesInJar), "On the ledge with three red circles. (in jar)" },
		{ Set.EnumKey(P1Id.BlueBoxSurroundedByFourStakesRightBox), "Blue box surrounded by four stakes. (right box)" },
		{ Set.EnumKey(P1Id.SecondFloorRooftopApartments), "Second floor rooftop of the stone face apartments." },
		{ Set.EnumKey(P1Id.FirstFloorApartments), "First floor of the stone face apartments." },
		{ Set.EnumKey(P1Id.SecondFloorApartments), "Second floor of the stone face apartments." },
		{ Set.EnumKey(P1Id.BlueBoxSurroundedByFourStakesLeftBox), "Blue box surrounded by four stakes. (left box)" },
		{ Set.EnumKey(P1Id.PlantsInTheShade), "Plants in the shade." },
		{ Set.EnumKey(P1Id.UnderTheStarGunsStorageArea), "Under the star in the GUN's storage area." },
		{ Set.EnumKey(P2Id.OnTheHeadMiddle), "On the head. (middle)" },
		{ Set.EnumKey(P2Id.OnTheHeadLeft), "On the head. (left)" },
		{ Set.EnumKey(P2Id.TearsOfGiant), "Tears of a giant." },
		{ Set.EnumKey(P2Id.StoneMonumentOfTheSun), "Stone monument of the sun." },
		{ Set.EnumKey(P2Id.TurtlesPathClose), "Turtle's path. (close)" },
		{ Set.EnumKey(P2Id.TurtlesPathFar), "Turtle's path. (far)" },
		{ Set.EnumKey(P2Id.BehindTheWaterPlant), "Behind the water plant." },
		{ Set.EnumKey(P2Id.EnchantedPillar), "Enchanted pillar." },
		{ Set.EnumKey(P2Id.BehindThePillarPlants), "Behind the pillar plants." },
		{ Set.EnumKey(P2Id.BlueBox), "Blue box." },
		{ Set.EnumKey(P2Id.EmeraldLeaf), "Emerald leaf." },
		{ Set.EnumKey(P2Id.BlueAndWhiteV), "Blue and white \"V\"." },
		{ Set.EnumKey(P2Id.SecondFloorApartments), "Second floor of the stone face apartments." },
		{ Set.EnumKey(P2Id.BehindTheRubble), "Behind the rubble." },
		{ Set.EnumKey(P2Id.BlueAndWhiteStripedPillar), "Blue and white striped pillar." },
		{ Set.EnumKey(P2Id.ACoconutBigOasis), "A coconut? (big oasis)" },
		{ Set.EnumKey(P2Id.TwoHugePillars), "Two huge pillars." },
		{ Set.EnumKey(P2Id.BlueAndWhiteStripedTunnelCorner), "Blue and white striped tunnel. (corner)" },
		{ Set.EnumKey(P2Id.InTheCornerOfRoomWithHeiroglyphics), "In the corner of the room covered with hieroglyphics." },
		{ Set.EnumKey(P2Id.JarSurroundedByThreeStakes), "A jar surrounded by three stakes." },
		{ Set.EnumKey(P2Id.StoneStatuesTreasure), "Stone statue's treasure." },
		{ Set.EnumKey(P2Id.ByTheGiantsChair), "By the giant's chair." },
		{ Set.EnumKey(P2Id.ACoconutPeriod), "A coconut?." },
		{ Set.EnumKey(P2Id.UnderneathPlatformWithFourStakes), "Underneath the platform with four stakes." },
		{ Set.EnumKey(P2Id.BlueAndWhiteStripedTunnelSubmerged), "Blue and white striped tunnel. (submerged)" },
		{ Set.EnumKey(P2Id.RazorPlant), "Razor plant." },
		{ Set.EnumKey(P2Id.GunsMiniStorageAreaUnguarded), "GUN's mini storage area. (unguarded)" },
		{ Set.EnumKey(P2Id.GunsMiniStorageAreaGuarded), "GUN's mini storage area. (guarded)" },
		{ Set.EnumKey(P2Id.GunsJar), "GUN's jar?" },
		{ Set.EnumKey(P2Id.JarStoragePlace), "Jar storage place." },
		{ Set.EnumKey(P2Id.ACoconutSmallOasis), "A coconut? (small oasis)" },
		{ Set.EnumKey(P3Id.UnderAChinLeft), "Under a chin. (left)" },
		{ Set.EnumKey(P3Id.UnderAChinRight), "Under a chin. (right)" },
		{ Set.EnumKey(P3Id.OnTheTiltedPillar), "On the tilted pillar." },
		{ Set.EnumKey(P3Id.OasisJailPeriod), "Oasis jail." },
		{ Set.EnumKey(P3Id.OasisJail), "Oasis jail" },
		{ Set.EnumKey(P3Id.OnTheBiggestTurtleShellStatic), "On the biggest turtle shell. (static)" },
		{ Set.EnumKey(P3Id.BullsEye), "Bull's eye!" },
		{ Set.EnumKey(P3Id.PlantsInTheShade), "Plants in the shade." },
		{ Set.EnumKey(P3Id.BetweenTheSunsFacingEachOtherFar), "Between the suns facing each other. (far)" },
		{ Set.EnumKey(P3Id.BetweenTheSunsFacingEachOtherNear), "Between the suns facing each other. (near)" },
		{ Set.EnumKey(P3Id.FishFood), "Fish food." },
		{ Set.EnumKey(P3Id.RedFlowerInTheWaterJail), "A red flower in the water? (jail)" },
		{ Set.EnumKey(P3Id.RedFlowerInTheWaterFarPond), "A red flower in the water? (far pond)" },
		{ Set.EnumKey(P3Id.BeneathApartments), "Beneath the stone face apartments." },
		{ Set.EnumKey(P3Id.EnchantedPillar), "Enchanted pillar." },
		{ Set.EnumKey(P3Id.OnTopOfAPalmTree), "On top of a palm tree." },
		{ Set.EnumKey(P3Id.DryLagoonThermometer), "Dry Lagoon thermometer." },
		{ Set.EnumKey(P3Id.CircleAroundTheSmallSun), "Circle around the small sun." },
		{ Set.EnumKey(P3Id.OnTheBiggestTurtleShellMoving), "On the biggest turtle shell. (moving)" },
		{ Set.EnumKey(P3Id.FloatingWithButterflies), "Floating with butterflies." },
		{ Set.EnumKey(P3Id.MovingBetweenBigAndSmallPillars), "Moving between the big and small pillars." },
		{ Set.EnumKey(P3Id.GoUpAndDownStairs), "Go up and down the stairs." },
		{ Set.EnumKey(P3Id.TurtlesTunnelMoving), "Turtle's tunnel. (moving)" },
		{ Set.EnumKey(P3Id.CircleAroundTheTiltedPillar), "Circle around the tilted pillar." },
		{ Set.EnumKey(P3Id.PlaceWhereWaterComesFrom), "The place where water comes from." },
		{ Set.EnumKey(P3Id.TurtlesTunnelStatic), "Turtle's tunnel. (static)" },
		{ Set.EnumKey(P3Id.UnderTurtlesFace), "Under the turtle's face." },
		{ Set.EnumKey(P3Id.InFrontOfWhiteBricks), "In front of the white bricks." },
		{ Set.EnumKey(P3Id.ButterflysTreasure), "Butterfly's treasure." }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string>();

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(DryLagoon.PieceToHint, DryLagoon.ImpossiblePieces);

	internal enum EnemyId {
		GunsGuardForTheStorageArea = 0x050A,
		ProtectorOfThePond = 0x060A,
		ProtectorOfTheJarLeft = 0x070A,
		ProtectorOfTheJarRight = 0x080A,
		GunsGuardOfTheStorageArea = 0x090A
	}

	internal enum P1Id {
		OnTheLedgeWithThreeRedCirclesOutJar = 0x0001,
		Offering = 0x0101,
		OnAHexagonPillarApartment = 0x0201,
		OnAHexagonPillarHeads = 0x0301,
		InBetweenMiniPillars = 0x0401,
		RedFlowersAndRedPillar = 0x0501,
		ForgottenLittleBoat = 0x0601,
		ByTheFarAwayPond = 0x0701,
		ByTheFootOfAShell = 0x0801,
		OutsideAJailCell = 0x0901,
		UnderwaterBalconyApartments = 0x0A01,
		UnderwaterBalconyTurtle = 0x0B01,
		ALotOfSquareFacesClose = 0x0C01,
		ALotOfSquareFacesFar = 0x0D01,
		BlueAndWhiteV = 0x0E01,
		StoneStatuesTreasure = 0x0F01,
		BlueStripedHeadBigOasis = 0x1001,
		BlueStripedHeadSmallOasis = 0x1101,
		GreenPool = 0x1201,
		ThePoolInFrontOfWall = 0x1301,
		GunsStorageAreaRight = 0x1401,
		GunsStorageAreaLeft = 0x1501,
		HugeScreenJars = 0x1601,
		HugeScreenPool = 0x1701,
		OnTheLedgeWithThreeRedCirclesInJar = 0x0003,
		BlueBoxSurroundedByFourStakesRightBox = 0x0103,
		SecondFloorRooftopApartments = 0x0203,
		FirstFloorApartments = 0x0303,
		SecondFloorApartments = 0x0403,
		BlueBoxSurroundedByFourStakesLeftBox = 0x0503,
		PlantsInTheShade = 0x0603,
		UnderTheStarGunsStorageArea = 0x0703
	}

	internal enum P2Id {
		OnTheHeadMiddle = 0x0000,
		OnTheHeadLeft = 0x0100,
		TearsOfGiant = 0x0200,
		StoneMonumentOfTheSun = 0x0300,
		TurtlesPathClose = 0x0400,
		TurtlesPathFar = 0x0500,
		BehindTheWaterPlant = 0x0600,
		EnchantedPillar = 0x0700,
		BehindThePillarPlants = 0x0002,
		BlueBox = 0x0102,
		EmeraldLeaf = 0x0202,
		BlueAndWhiteV = 0x0302,
		SecondFloorApartments = 0x0402,
		BehindTheRubble = 0x0502,
		BlueAndWhiteStripedPillar = 0x0702,
		ACoconutBigOasis = 0x0005,
		TwoHugePillars = 0x0105,
		BlueAndWhiteStripedTunnelCorner = 0x0205,
		InTheCornerOfRoomWithHeiroglyphics = 0x0305,
		JarSurroundedByThreeStakes = 0x0405,
		StoneStatuesTreasure = 0x0505,
		ByTheGiantsChair = 0x0605,
		ACoconutPeriod = 0x0705,
		UnderneathPlatformWithFourStakes = 0x0805,
		BlueAndWhiteStripedTunnelSubmerged = 0x0905,
		RazorPlant = 0x0A05,
		GunsMiniStorageAreaUnguarded = 0x0B05,
		GunsMiniStorageAreaGuarded = 0x0C05,
		GunsJar = 0x0D05,
		JarStoragePlace = 0x0E05,
		ACoconutSmallOasis = 0x0F05
	}

	internal enum P3Id {
		UnderAChinLeft = 0x0004,
		UnderAChinRight = 0x0104,
		OnTheTiltedPillar = 0x0204,
		OasisJailPeriod = 0x0304,
		OasisJail = 0x0404,
		OnTheBiggestTurtleShellStatic = 0x0504,
		BullsEye = 0x0604,
		PlantsInTheShade = 0x0704,
		BetweenTheSunsFacingEachOtherFar = 0x0804,
		BetweenTheSunsFacingEachOtherNear = 0x0904,
		FishFood = 0x0A04,
		RedFlowerInTheWaterJail = 0x0B04,
		RedFlowerInTheWaterFarPond = 0x0C04,
		BeneathApartments = 0x0D04,
		EnchantedPillar = 0x0E04,
		OnTopOfAPalmTree = 0x0F04,
		DryLagoonThermometer = 0x0007,
		CircleAroundTheSmallSun = 0x0107,
		OnTheBiggestTurtleShellMoving = 0x0207,
		FloatingWithButterflies = 0x0307,
		MovingBetweenBigAndSmallPillars = 0x0407,
		GoUpAndDownStairs = 0x0507,
		TurtlesTunnelMoving = 0x0607,
		CircleAroundTheTiltedPillar = 0x0707,
		PlaceWhereWaterComesFrom = 0x0208,
		TurtlesTunnelStatic = 0x0308,
		UnderTurtlesFace = 0x0508,
		InFrontOfWhiteBricks = 0x0608,
		ButterflysTreasure = 0x0708
	}
}
