namespace sa2_hunting_teacher.Rouge;

public class EggQuarters(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.EggQuarters;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.ShadowOfScurryingBugFish, P2Id.OnANeedle, P3Id.UnderTheScorpion, EggQuarters.PieceToHint),
		Set.Create(P1Id.StoneWallsOnRightLeftAbove, P2Id.ADarkRoomRed, P3Id.InTheMiddleOfTheRoom, EggQuarters.PieceToHint),
		Set.Create(P1Id.WingsButCantFly, P2Id.SnakeFlameExposed, P3Id.RidingTheGoldenCondor, EggQuarters.PieceToHint),
		Set.Create(P1Id.HexagonalCeilingFish, P2Id.TwoPairsDifferentLengthLegsRed, P3Id.GlowingHeiroglyphics, EggQuarters.PieceToHint),
		Set.Create(P1Id.OnWhiteEggmanMark, P2Id.GorillasHideout, P3Id.PlayVolleyballWithMouth, EggQuarters.PieceToHint),
		Set.Create(P1Id.AQuietPlace, P2Id.TwoPairsDifferentLengthLegsGreen, P3Id.FollowTheRings, EggQuarters.PieceToHint),
		Set.Create(P1Id.RedAndSilverMovingBackAndForth, P2Id.SkullsRoom, P3Id.APlaceSurroundedByBlackAndYellow, EggQuarters.PieceToHint),
		Set.Create(P1Id.GlowingRedSquare, P2Id.WhiteMiddleFinger, P3Id.HolySacrifice, EggQuarters.PieceToHint),
		Set.Create(P1Id.FullScaleEye, P2Id.SnakeFlameContainer, P3Id.ASkullMessage, EggQuarters.PieceToHint),
		Set.Create(P1Id.TwoFaces, P2Id.HiddenAncientWallPainting, P3Id.WanderingGhost, EggQuarters.PieceToHint),
		Set.Create(P1Id.AShadowStretchesBottomToTop, P2Id.AboveTheEntrance, P3Id.HotChao, EggQuarters.PieceToHint),
		Set.Create(P1Id.UpsideDownStairs, P2Id.ARoomWithHeiroglyphics, P3Id.ChippedPetal, EggQuarters.PieceToHint),
		Set.Create(P1Id.ShadowOfScurryingBugSnake, P2Id.KingAndServant, P3Id.InTheMiddleOfARoom, EggQuarters.PieceToHint),
		Set.Create(P1Id.HexagonalCeilingSnake, P2Id.BlueEyedEggman, P3Id.FloatingInTheStream, EggQuarters.PieceToHint),
		Set.Create(P1Id.UnderHeiroglyphics, P2Id.ADarkRoomGreen, P3Id.FollowTheLineOnTheWall, EggQuarters.PieceToHint),
		Set.Create(P1Id.FourPillarsExposed, P2Id.TheCondorSpreadsItsWings, P3Id.ASkull, EggQuarters.PieceToHint),
		Set.Create(P1Id.TheSkullLookingAtYouThroughCrack, P2Id.FirstPlaceYouLanded, P3Id.DarkChao, EggQuarters.PieceToHint),
		Set.Create(P1Id.TheHeadOfACondor, P2Id.OmochaoAndEggman, P3Id.DarkSonicAltar, EggQuarters.PieceToHint),
		Set.Create(P1Id.ThreeHands, P2Id.UnderTheTail, P3Id.SlowlySwimming, EggQuarters.PieceToHint),
		Set.Create(P1Id.InCenterOfX, P2Id.CenterOfTheRing, P3Id.ThickWall, EggQuarters.PieceToHint),
		Set.Create(P1Id.OnTheScorpion, P2Id.TwoPairDifferentLengthLegs, P3Id.SkullsFacingEachOther, EggQuarters.PieceToHint),
		Set.Create(P1Id.TheSecondRoom, P2Id.SleepingUnderCoffin, P3Id.CondorsEggSnake, EggQuarters.PieceToHint),
		Set.Create(P1Id.TheHeadOfTheCondor, P2Id.TwoSmeltingFurnaces, P3Id.SecondAfterNextStoneRing, EggQuarters.PieceToHint),
		Set.Create(P1Id.InvisibleContainer, P2Id.SixWhiteEggs, P3Id.BlackBirdInShadow, EggQuarters.PieceToHint),
		Set.Create(P1Id.RedPillarTriangle, EnemyId.YellowHeadGreen, P3Id.ChaoSignOnTheFloor, EggQuarters.PieceToHint),
		Set.Create(EnemyId.YellowHeadRed, P2Id.UnderTheTreasure, P3Id.DarkSonicFish, EggQuarters.PieceToHint),
		Set.Create(EnemyId.RedWarriorRed, P2Id.FlamesFacingEachOther, P3Id.CondorsEggScorpion, EggQuarters.PieceToHint),
		Set.Create(EnemyId.RedWarriorGreen, P2Id.ThreeTriangles, P3Id.DarkRedAndWhiteStripes, EggQuarters.PieceToHint),
		Set.Create(P1Id.SixEggmanMarks, P2Id.UnderTheHeiroglyphics, P3Id.ThreeSnakeBrothers, EggQuarters.PieceToHint),
		Set.Create(P1Id.BrownBetweenBlack, P2Id.TwoBeautifulWomenWithFishFaces, P3Id.ChaoSymbolOnTheWall, EggQuarters.PieceToHint),
		Set.Create(P1Id.GoldenCondor, EnemyId.TheForeman, P3Id.SemiDarkEggman, EggQuarters.PieceToHint),
		Set.Create(P1Id.FourPillarsContainer, EnemyId.LifeSentence, P3Id.DarkSonicFish, EggQuarters.PieceToHint),
		Set.Create(P1Id.HolyAltar, EnemyId.FearOfHeights, P3Id.DarkSonicAltar, EggQuarters.PieceToHint),
		Set.Create(P1Id.BlackContainer, P2Id.HandInTheCenter, P3Id.DarkChao, EggQuarters.PieceToHint),
		Set.Create(P1Id.HugeShadowRoom, P2Id.UnderTheLowFlame, P3Id.HotChao, EggQuarters.PieceToHint),
	];

	public override string ToString() => "Egg Quarters";

	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(EnemyId.YellowHeadRed), "Yellow head. (red)" },
		{ Set.EnumKey(EnemyId.RedWarriorRed), "Red warrior. (red)" },
		{ Set.EnumKey(EnemyId.RedWarriorGreen), "Red warrior. (green)" },
		{ Set.EnumKey(EnemyId.YellowHeadGreen), "Yellow head. (green)" },
		{ Set.EnumKey(EnemyId.TheForeman), "The Foreman???" },
		{ Set.EnumKey(EnemyId.LifeSentence), "Life sentence..." },
		{ Set.EnumKey(EnemyId.FearOfHeights), "Fear of heights." },
		{ Set.EnumKey(P1Id.ShadowOfScurryingBugFish), "In the shadow of the scurrying bug. (Fish)" },
		{ Set.EnumKey(P1Id.StoneWallsOnRightLeftAbove), "Stone walls on the right, left and above." },
		{ Set.EnumKey(P1Id.WingsButCantFly), "Wings but can't fly." },
		{ Set.EnumKey(P1Id.HexagonalCeilingFish), "The hexagonal ceiling. (Fish)" },
		{ Set.EnumKey(P1Id.OnWhiteEggmanMark), "On the white Eggman mark." },
		{ Set.EnumKey(P1Id.AQuietPlace), "A quiet place." },
		{ Set.EnumKey(P1Id.SixEggmanMarks), "Six Eggman marks?" },
		{ Set.EnumKey(P1Id.RedAndSilverMovingBackAndForth), "Red and silver moving back and forth." },
		{ Set.EnumKey(P1Id.GlowingRedSquare), "A glowing red square." },
		{ Set.EnumKey(P1Id.FullScaleEye), "Full-scale eye?" },
		{ Set.EnumKey(P1Id.TwoFaces), "Two faces." },
		{ Set.EnumKey(P1Id.AShadowStretchesBottomToTop), "A shadow that stretches from the bottom to the top." },
		{ Set.EnumKey(P1Id.UpsideDownStairs), "Upside down stairs." },
		{ Set.EnumKey(P1Id.ShadowOfScurryingBugSnake), "In the shadow of the scurrying bug. (Snake)" },
		{ Set.EnumKey(P1Id.HexagonalCeilingSnake), "The hexagonal ceiling. (Snake)" },
		{ Set.EnumKey(P1Id.UnderHeiroglyphics), "Under the hieroglyphics." },
		{ Set.EnumKey(P1Id.FourPillarsExposed), "Four pillars. (exposed)" },
		{ Set.EnumKey(P1Id.TheSkullLookingAtYouThroughCrack), "The skull is looking at you through a crack." },
		{ Set.EnumKey(P1Id.TheHeadOfACondor), "The head of a condor." },
		{ Set.EnumKey(P1Id.ThreeHands), "Three hands." },
		{ Set.EnumKey(P1Id.InCenterOfX), "In the center of the \"X\"." },
		{ Set.EnumKey(P1Id.OnTheScorpion), "On the scorpion." },
		{ Set.EnumKey(P1Id.TheSecondRoom), "The second room." },
		{ Set.EnumKey(P1Id.TheHeadOfTheCondor), "The head of the condor." },
		{ Set.EnumKey(P1Id.InvisibleContainer), "Invisible container." },
		{ Set.EnumKey(P1Id.RedPillarTriangle), "A red pillar triangle." },
		{ Set.EnumKey(P1Id.BrownBetweenBlack), "Brown between black." },
		{ Set.EnumKey(P1Id.GoldenCondor), "Golden condor." },
		{ Set.EnumKey(P1Id.FourPillarsContainer), "Four pillars. (container)" },
		{ Set.EnumKey(P1Id.HolyAltar), "Holy altar." },
		{ Set.EnumKey(P1Id.BlackContainer), "A black container." },
		{ Set.EnumKey(P1Id.HugeShadowRoom), "Huge shadow room." },
		{ Set.EnumKey(P2Id.OnANeedle), "On a needle." },
		{ Set.EnumKey(P2Id.ADarkRoomRed), "A dark room. (red)" },
		{ Set.EnumKey(P2Id.SnakeFlameExposed), "Snake flame. (exposed)" },
		{ Set.EnumKey(P2Id.TwoPairsDifferentLengthLegsRed), "Two pairs of different length legs. (red)" },
		{ Set.EnumKey(P2Id.AboveTheEntrance), "Above the entrance." },
		{ Set.EnumKey(P2Id.HiddenAncientWallPainting), "Hidden ancient wall painting." },
		{ Set.EnumKey(P2Id.UnderTheHeiroglyphics), "Under the hieroglyphics." },
		{ Set.EnumKey(P2Id.TwoPairsDifferentLengthLegsGreen), "Two pairs of different length legs. (green)" },
		{ Set.EnumKey(P2Id.SkullsRoom), "Skull's room." },
		{ Set.EnumKey(P2Id.WhiteMiddleFinger), "White middle finger." },
		{ Set.EnumKey(P2Id.SnakeFlameContainer), "Snake flame. (container)" },
		{ Set.EnumKey(P2Id.GorillasHideout), "Gorilla's hideout." },
		{ Set.EnumKey(P2Id.ARoomWithHeiroglyphics), "A room with hieroglyphics." },
		{ Set.EnumKey(P2Id.KingAndServant), "King and the servant." },
		{ Set.EnumKey(P2Id.TheCondorSpreadsItsWings), "The condor spreads its wings." },
		{ Set.EnumKey(P2Id.ADarkRoomGreen), "A dark room. (green)" },
		{ Set.EnumKey(P2Id.BlueEyedEggman), "Blue-eyed Eggman." },
		{ Set.EnumKey(P2Id.FirstPlaceYouLanded), "First place you landed." },
		{ Set.EnumKey(P2Id.OmochaoAndEggman), "Omochao and Eggman." },
		{ Set.EnumKey(P2Id.UnderTheTail), "Under the tail." },
		{ Set.EnumKey(P2Id.CenterOfTheRing), "Center of the ring." },
		{ Set.EnumKey(P2Id.TwoPairDifferentLengthLegs), "Two pair of different length legs." },
		{ Set.EnumKey(P2Id.SleepingUnderCoffin), "Sleeping under a coffin." },
		{ Set.EnumKey(P2Id.TwoSmeltingFurnaces), "Two smelting furnaces." },
		{ Set.EnumKey(P2Id.SixWhiteEggs), "Six white eggs." },
		// { Set.EnumKey(P2Id.UnderTheBellyImpossible), "Under the belly." },
		{ Set.EnumKey(P2Id.TwoBeautifulWomenWithFishFaces), "Two beautiful women with fish faces." },
		{ Set.EnumKey(P2Id.UnderTheTreasure), "Under the treasure." },
		{ Set.EnumKey(P2Id.FlamesFacingEachOther), "Flames facing each other." },
		{ Set.EnumKey(P2Id.ThreeTriangles), "Three triangles." },
		{ Set.EnumKey(P2Id.HandInTheCenter), "Hand in the center." },
		{ Set.EnumKey(P2Id.UnderTheLowFlame), "Under the low flame." },
		{ Set.EnumKey(P3Id.SemiDarkEggman), "Semi-dark Eggman." },
		{ Set.EnumKey(P3Id.ChaoSymbolOnTheWall), "Chao symbol on the wall." },
		{ Set.EnumKey(P3Id.DarkRedAndWhiteStripes), "Dark red and white stripes." },
		{ Set.EnumKey(P3Id.CondorsEggScorpion), "Condor's egg. (Scorpion)" },
		{ Set.EnumKey(P3Id.DarkSonicFish), "Dark Sonic. (Fish)" },
		{ Set.EnumKey(P3Id.ChaoSignOnTheFloor), "Chao sign on the floor." },
		{ Set.EnumKey(P3Id.BlackBirdInShadow), "Black bird in the shadow." },
		{ Set.EnumKey(P3Id.SecondAfterNextStoneRing), "Second after next to the stone ring." },
		{ Set.EnumKey(P3Id.CondorsEggSnake), "Condor's egg. (Snake)" },
		{ Set.EnumKey(P3Id.SkullsFacingEachOther), "Skulls facing each other." },
		{ Set.EnumKey(P3Id.ThickWall), "A thick wall." },
		{ Set.EnumKey(P3Id.ChippedPetal), "Chipped petal." },
		{ Set.EnumKey(P3Id.DarkSonicAltar), "Dark Sonic. (Altar)" },
		{ Set.EnumKey(P3Id.DarkChao), "Dark Chao." },
		{ Set.EnumKey(P3Id.ASkull), "A skull." },
		{ Set.EnumKey(P3Id.HotChao), "Hot Chao..." },
		{ Set.EnumKey(P3Id.FollowTheLineOnTheWall), "Follow the line on the wall." },
		{ Set.EnumKey(P3Id.WanderingGhost), "Wandering ghost..." },
		{ Set.EnumKey(P3Id.SlowlySwimming), "Slowly swimming..." },
		{ Set.EnumKey(P3Id.FloatingInTheStream), "Floating in the stream..." },
		{ Set.EnumKey(P3Id.HolySacrifice), "Holy sacrifice." },
		{ Set.EnumKey(P3Id.ASkullMessage), "A skull message." },
		{ Set.EnumKey(P3Id.FollowTheRings), "Follow the rings." },
		{ Set.EnumKey(P3Id.PlayVolleyballWithMouth), "Play volleyball with a mouth???" },
		{ Set.EnumKey(P3Id.ThreeSnakeBrothers), "Three snake brothers." },
		{ Set.EnumKey(P3Id.InTheMiddleOfARoom), "In the middle of a room." },
		{ Set.EnumKey(P3Id.APlaceSurroundedByBlackAndYellow), "A place surrounded by black and yellow." },
		{ Set.EnumKey(P3Id.GlowingHeiroglyphics), "Glowing hieroglyphics." },
		{ Set.EnumKey(P3Id.RidingTheGoldenCondor), "Riding the golden condor." },
		{ Set.EnumKey(P3Id.InTheMiddleOfTheRoom), "In the middle of the room." },
		{ Set.EnumKey(P3Id.UnderTheScorpion), "Under the scorpion." },
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(P2Id.UnderTheBellyImpossible), "Under the belly." }
	};

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(EggQuarters.PieceToHint, EggQuarters.ImpossiblePieces);

	internal enum EnemyId {
		YellowHeadRed = 0x000A,
		RedWarriorRed = 0x010A,
		RedWarriorGreen = 0x020A,
		YellowHeadGreen = 0x030A,
		TheForeman = 0x040A,
		LifeSentence = 0x050A,
		FearOfHeights = 0x060A
	}

	internal enum P1Id {
		ShadowOfScurryingBugFish = 0x0001,
		StoneWallsOnRightLeftAbove = 0x0101,
		WingsButCantFly = 0x0201,
		HexagonalCeilingFish = 0x0301,
		OnWhiteEggmanMark = 0x0401,
		AQuietPlace = 0x0501,
		SixEggmanMarks = 0x0601,
		RedAndSilverMovingBackAndForth = 0x0701,
		GlowingRedSquare = 0x0801,
		FullScaleEye = 0x0901,
		TwoFaces = 0x0A01,
		AShadowStretchesBottomToTop = 0x0B01,
		UpsideDownStairs = 0x0C01,
		ShadowOfScurryingBugSnake = 0x0D01,
		HexagonalCeilingSnake = 0x0E01,
		UnderHeiroglyphics = 0x0F01,
		FourPillarsExposed = 0x1001,
		TheSkullLookingAtYouThroughCrack = 0x1101,
		TheHeadOfACondor = 0x1201,
		ThreeHands = 0x1301,
		InCenterOfX = 0x1401,
		OnTheScorpion = 0x1501,
		TheSecondRoom = 0x1601,
		TheHeadOfTheCondor = 0x1701,
		InvisibleContainer = 0x0003,
		RedPillarTriangle = 0x0103,
		BrownBetweenBlack = 0x0203,
		GoldenCondor = 0x0303,
		FourPillarsContainer = 0x0403,
		HolyAltar = 0x0503,
		BlackContainer = 0x0603,
		HugeShadowRoom = 0x0703
	}

	internal enum P2Id {
		OnANeedle = 0x0000,
		ADarkRoomRed = 0x0100,
		SnakeFlameExposed = 0x0200,
		TwoPairsDifferentLengthLegsRed = 0x0300,
		AboveTheEntrance = 0x0400,
		HiddenAncientWallPainting = 0x0500,
		UnderTheHeiroglyphics = 0x0600,
		TwoPairsDifferentLengthLegsGreen = 0x0700,
		SkullsRoom = 0x0002,
		WhiteMiddleFinger = 0x0102,
		SnakeFlameContainer = 0x0202,
		GorillasHideout = 0x0302,
		ARoomWithHeiroglyphics = 0x0402,
		KingAndServant = 0x0502,
		TheCondorSpreadsItsWings = 0x0602,
		ADarkRoomGreen = 0x0702,
		BlueEyedEggman = 0x0005,
		FirstPlaceYouLanded = 0x0105,
		OmochaoAndEggman = 0x0205,
		UnderTheTail = 0x0305,
		CenterOfTheRing = 0x0405,
		TwoPairDifferentLengthLegs = 0x0505,
		SleepingUnderCoffin = 0x0605,
		TwoSmeltingFurnaces = 0x0705,
		SixWhiteEggs = 0x0805,
		UnderTheBellyImpossible = 0x0905, // Impossible piece
		TwoBeautifulWomenWithFishFaces = 0x0A05,
		UnderTheTreasure = 0x0B05,
		FlamesFacingEachOther = 0x0C05,
		ThreeTriangles = 0x0D05,
		HandInTheCenter = 0x0E05,
		UnderTheLowFlame = 0x0F05
	}

	internal enum P3Id {
		SemiDarkEggman = 0x0004,
		ChaoSymbolOnTheWall = 0x0104,
		DarkRedAndWhiteStripes = 0x0204,
		CondorsEggScorpion = 0x0304,
		DarkSonicFish = 0x0404,
		ChaoSignOnTheFloor = 0x0504,
		BlackBirdInShadow = 0x0604,
		SecondAfterNextStoneRing = 0x0704,
		CondorsEggSnake = 0x0804,
		SkullsFacingEachOther = 0x0904,
		ThickWall = 0x0A04,
		ChippedPetal = 0x0B04,
		DarkSonicAltar = 0x0C04,
		DarkChao = 0x0D04,
		ASkull = 0x0E04,
		HotChao = 0x0F04,
		FollowTheLineOnTheWall = 0x0007,
		WanderingGhost = 0x0107,
		SlowlySwimming = 0x0207,
		FloatingInTheStream = 0x0307,
		HolySacrifice = 0x0407,
		ASkullMessage = 0x0507,
		FollowTheRings = 0x0607,
		PlayVolleyballWithMouth = 0x0707,
		ThreeSnakeBrothers = 0x0008,
		InTheMiddleOfARoom = 0x0208,
		APlaceSurroundedByBlackAndYellow = 0x0308,
		GlowingHeiroglyphics = 0x0408,
		RidingTheGoldenCondor = 0x0508,
		InTheMiddleOfTheRoom = 0x0608,
		UnderTheScorpion = 0x0708
	}
}
