using sa2_hunting_teacher.Knuckles;

namespace sa2_hunting_teacher.Rouge;

public class MadSpace(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.MadSpace;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.BlueLightBalconyYellow, P2Id.FloatingPlatformGravityMeteoriteFarOpening, P3Id.BlueLightBalconyStatic, MadSpace.PieceToHint),
		Set.Create(P1Id.ItsHotInside, P2Id.RedLightBalcony, P3Id.ContainerWithoutOpening, MadSpace.PieceToHint),
		Set.Create(P1Id.ContainerWithNoOpening, P2Id.LonelyStarPrairie, P3Id.DangerousMoonSmall, MadSpace.PieceToHint),
		Set.Create(EnemyId.EvilLiquid, P2Id.JewelGrowingRockLow, P3Id.HugePaperWeight, MadSpace.PieceToHint),
		Set.Create(P1Id.OctagonalMissileLaunchingPadFarRocket, P2Id.CrescentMoonGreenGlowing, P3Id.DangerousStar, MadSpace.PieceToHint),
		Set.Create(P1Id.YellowCircleCW, P2Id.TopOfCapsuleBottom, P3Id.OddMoon, MadSpace.PieceToHint),
		Set.Create(P1Id.BoxSurroundedByRedLights, P2Id.StarUnderRoof, P3Id.BetweenMachinesThreeLegs, MadSpace.PieceToHint),
		Set.Create(P1Id.LonelyHouseCrystal, P2Id.TopOfCapsuleTop, P3Id.StarByBurningWatchman, MadSpace.PieceToHint),
		Set.Create(P1Id.ThreeColoredContainerYellow, P2Id.FlyingContainerBlack, P3Id.WhereAllLightsGather, MadSpace.PieceToHint),
		Set.Create(EnemyId.BlueEnemy, P2Id.UnderBlackBox, P3Id.ThreeColoredContainer, MadSpace.PieceToHint),
		Set.Create(P1Id.ContainerWithinContainer, EnemyId.Watchman, P3Id.BunchOfBlackContainersAtBaseStatic, MadSpace.PieceToHint),
		Set.Create(P1Id.ThreeColoredContainerBlue, P2Id.TopLegMachine1, P3Id.StickingStar, MadSpace.PieceToHint),
		Set.Create(P1Id.RedLightBalcony, P2Id.BetweenRedNails, P3Id.DangerousMoonLarge, MadSpace.PieceToHint),
		Set.Create(P1Id.BlueLightCircle, P2Id.StarUnderLight, P3Id.MoonOnTheCeiling, MadSpace.PieceToHint),
		Set.Create(P1Id.Machine1ThreeLegs, P2Id.BetweenTwoMoons, P3Id.VeryYellowPlatformStatic, MadSpace.PieceToHint),
		Set.Create(P1Id.ContainerNotFloating, P2Id.FloatingPlatformGravityMeteoriteNearOpening, P3Id.LonelyLightInDark, MadSpace.PieceToHint),
		Set.Create(P1Id.LonelyHouseOmochao, P2Id.TopLegMachine3, P3Id.DangerousMoonPlanet, MadSpace.PieceToHint),
		Set.Create(P1Id.DancingWoodenBoxGrass, P2Id.ToCloseForestSeeTrees, P3Id.MoonBetweenSomething, MadSpace.PieceToHint),
		Set.Create(EnemyId.MachineProtectsStorage, P2Id.WrongLight, P3Id.BurningRockSeed, MadSpace.PieceToHint),
		Set.Create(P1Id.BetweenTallGuys, P2Id.BlueInYellow, P3Id.CraterCart, MadSpace.PieceToHint),
		Set.Create(P1Id.Machine3ThreeLegs, EnemyId.MachineProtectsStorage, P3Id.BaseOfTiltedLight, MadSpace.PieceToHint),
		Set.Create(P1Id.HouseMeteoritesOwner, EnemyId.MachineProtectsStorage, P3Id.StarRedLightShinesOn, MadSpace.PieceToHint),
		Set.Create(P1Id.DancingWoodenBoxGrass, P2Id.FlyingContainerRed, P3Id.BlackContainerBalcony, MadSpace.PieceToHint),
		Set.Create(P1Id.RedNail, P2Id.ContainerWithinContainer, P3Id.DangerousMoonPlanet, MadSpace.PieceToHint),
		Set.Create(P1Id.WrongLight, P2Id.StickingStarNearArk, P3Id.DangerousMoonPlanet, MadSpace.PieceToHint),
		Set.Create(P1Id.No2Leg, P2Id.MessyStorage, P3Id.LonelyLightInDark, MadSpace.PieceToHint),
		Set.Create(P1Id.YellowCircleCCW, P2Id.StickingStarFarRocket, P3Id.LonelyLightInDark, MadSpace.PieceToHint),
		Set.Create(P1Id.PropellorMachineThreeLegs, P2Id.StickingStarFarArk, P3Id.StarByBurningWatchman, MadSpace.PieceToHint),
		Set.Create(P1Id.BlackContainerBalcony, P2Id.LightDidntGrowUp, P3Id.BetweenMachinesThreeLegs, MadSpace.PieceToHint),
		Set.Create(P1Id.BluLightBalconyBlue, P2Id.JewelGrowingRockHigh, P3Id.BetweenMachinesThreeLegs, MadSpace.PieceToHint),
		Set.Create(P1Id.TiredLight, P2Id.StickingStarFarRocket, P3Id.BunchOfBlackContainersAtBaseStatic, MadSpace.PieceToHint),
		Set.Create(P1Id.ThreeColoredContainerRed, P2Id.SpinningBoxAboveMeteorite, P3Id.LonelyLightInDark, MadSpace.PieceToHint),
		Set.Create(P1Id.OctagonalMissileLaunchingPadNearRocket, P2Id.SadAndLonelyLight, P3Id.BunchOfBlackContainersAtBaseStatic, MadSpace.PieceToHint),
		Set.Create(P1Id.GreenInABowl, P2Id.FlyingContainerRed, P3Id.ThreeColoredContainer, MadSpace.PieceToHint),
		Set.Create(P1Id.TiltedLight, P2Id.FlyingContainerRed, P3Id.ContainerWithoutOpening, MadSpace.PieceToHint),
		Set.Create(P1Id.DancingWoodenBoxGrass, P2Id.CrescentMoonGreenGlowing, P3Id.RedSquare, MadSpace.PieceToHint),
	];

	public override string ToString() => "Mad Space";

	public override Dictionary<int, string> PieceToHintInstance => MadSpace.PieceToHint;
	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(EnemyId.Watchman), "Watchman of the yellow balcony" },
		{ Set.EnumKey(EnemyId.EvilLiquid), "Evil liquid" },
		{ Set.EnumKey(EnemyId.BlueEnemy), "The blue enemy on the blue stand" },
		{ Set.EnumKey(EnemyId.MachineProtectsStorage), "The machine that protects the storage container" },
		{ Set.EnumKey(P1Id.RedLightBalcony), "Red light balcony" },
		{ Set.EnumKey(P1Id.BluLightBalconyBlue), "Blue light balcony (blue)" },
		{ Set.EnumKey(P1Id.BlueLightBalconyYellow), "Blue light balcony (yellow)" },
		{ Set.EnumKey(P1Id.BlackContainerBalcony), "Black container balcony" },
		{ Set.EnumKey(P1Id.OctagonalMissileLaunchingPadNearRocket), "Octagonal missile launching pad (near rocket)" },
		{ Set.EnumKey(P1Id.OctagonalMissileLaunchingPadFarRocket), "Octagonal missile launching pad (far from rocket)" },
		{ Set.EnumKey(P1Id.ThreeColoredContainerBlue), "Three colored container (blue)" },
		{ Set.EnumKey(P1Id.ThreeColoredContainerYellow), "Three colored container (yellow)" },
		{ Set.EnumKey(P1Id.ContainerWithNoOpening), "Container with no opening" },
		{ Set.EnumKey(P1Id.BlueLightCircle), "Blue light circle" },
		{ Set.EnumKey(P1Id.GreenInABowl), "Green in a bowl" },
		{ Set.EnumKey(P1Id.LonelyHouseCrystal), "Lonely house (crystal)" },
		{ Set.EnumKey(P1Id.TiltedLight), "Tilted light" },
		{ Set.EnumKey(P1Id.LonelyHouseOmochao), "Lonely house (Omochao)" },
		{ Set.EnumKey(P1Id.PropellorMachineThreeLegs), "Propellor of the machine with three legs" },
		{ Set.EnumKey(P1Id.Machine1ThreeLegs), "Machine no. 1 with three legs" },
		{ Set.EnumKey(P1Id.Machine3ThreeLegs), "Machine no. 3 with three legs" },
		{ Set.EnumKey(P1Id.RedNail), "Red nail" },
		{ Set.EnumKey(P1Id.No2Leg), "No.2 leg" },
		{ Set.EnumKey(P1Id.YellowCircleCCW), "Yellow light circle (CCW)" },
		{ Set.EnumKey(P1Id.YellowCircleCW), "Yellow light circle (CW)" },
		{ Set.EnumKey(P1Id.HouseMeteoritesOwner), "The house of the meteorite's owner" },
		{ Set.EnumKey(P1Id.WrongLight), "Wrong light" },
		{ Set.EnumKey(P1Id.TiredLight), "Tired light" },
		{ Set.EnumKey(P1Id.ContainerNotFloating), "The container that is not floating" },
		{ Set.EnumKey(P1Id.ThreeColoredContainerRed), "Three colored container (red)" },
		{ Set.EnumKey(P1Id.ContainerWithinContainer), "A container within a container" },
		{ Set.EnumKey(P1Id.BoxSurroundedByRedLights), "A box surrounded by red lights" },
		{ Set.EnumKey(P1Id.ItsHotInside), "It's hot inside" },
		{ Set.EnumKey(P1Id.DancingWoodenBoxGrass), "Dancing wooden box on the grass" },
		{ Set.EnumKey(P1Id.BetweenTallGuys), "Between the tall guys" },
		{ Set.EnumKey(P2Id.RedLightBalcony), "Red light balcony" },
		{ Set.EnumKey(P2Id.JewelGrowingRockHigh), "A jewel growing on a rock (high)" },
		{ Set.EnumKey(P2Id.JewelGrowingRockLow), "A jewel growing on a rock (low)" },
		{ Set.EnumKey(P2Id.TopOfCapsuleTop), "The top of the capsule (top)" },
		{ Set.EnumKey(P2Id.TopOfCapsuleBottom), "The top of the capsule (bottom)" },
		{ Set.EnumKey(P2Id.FloatingPlatformGravityMeteoriteFarOpening), "Floating platform of the gravity meteorite (far from opening)" },
		{ Set.EnumKey(P2Id.FloatingPlatformGravityMeteoriteNearOpening), "Floating platform of the gravity meteorite (near opening)" },
		{ Set.EnumKey(P2Id.ToCloseForestSeeTrees), "To close to the forest to see the trees" },
		{ Set.EnumKey(P2Id.FlyingContainerRed), "Flying container (red)" },
		{ Set.EnumKey(P2Id.FlyingContainerBlack), "Flying container (black)" },
		{ Set.EnumKey(P2Id.MessyStorage), "Messy storage" },
		{ Set.EnumKey(P2Id.ContainerWithinContainer), "A container within a container" },
		{ Set.EnumKey(P2Id.SpinningBoxAboveMeteorite), "The spinning box above the meteorite" },
		{ Set.EnumKey(P2Id.BetweenRedNails), "Between the red nails" },
		{ Set.EnumKey(P2Id.BlueInYellow), "Blue in yellow" },
		{ Set.EnumKey(P2Id.StarUnderLight), "The star under the light" },
		{ Set.EnumKey(P2Id.StickingStarFarArk), "Sticking star (far from ARK)" },
		{ Set.EnumKey(P2Id.StickingStarFarRocket), "Sticking star (far from rocket)" },
		{ Set.EnumKey(P2Id.StickingStarNearArk), "Sticking star (near ARK)" },
		{ Set.EnumKey(P2Id.LightDidntGrowUp), "The light that didn't grow up" },
		{ Set.EnumKey(P2Id.SadAndLonelyLight), "Sad dna lonely light" },
		{ Set.EnumKey(P2Id.UnderBlackBox), "Under the black box" },
		{ Set.EnumKey(P2Id.TopLegMachine1), "The top of the leg of machine no 1" },
		{ Set.EnumKey(P2Id.TopLegMachine3), "The top of the leg of machine no 3" },
		{ Set.EnumKey(P2Id.LonelyStarPrairie), "Lonely star on the prairie" },
		{ Set.EnumKey(P2Id.StarUnderRoof), "The star under a roof" },
		{ Set.EnumKey(P2Id.WrongLight), "Wrong light" },
		{ Set.EnumKey(P2Id.CrescentMoonGreenGlowing), "Crescent moon with green growing ... ?" },
		{ Set.EnumKey(P2Id.BetweenTwoMoons), "Between two moons" },
		{ Set.EnumKey(P3Id.WhereAllLightsGather), "Where all of the lights gather" },
		{ Set.EnumKey(P3Id.StickingStar), "Sticking star" },
		{ Set.EnumKey(P3Id.MoonBetweenSomething), "The moon between something" },
		{ Set.EnumKey(P3Id.OddMoon), "Odd moon" },
		{ Set.EnumKey(P3Id.StarRedLightShinesOn), "The star that the red light shines on" },
		{ Set.EnumKey(P3Id.DangerousMoonLarge), "Dangerous moon (large)" },
		{ Set.EnumKey(P3Id.DangerousMoonSmall), "Dangerous moon (small)" },
		{ Set.EnumKey(P3Id.BaseOfTiltedLight), "At the base of the tilted light" },
		{ Set.EnumKey(P3Id.LonelyLightInDark), "Lonely light in the dark" },
		{ Set.EnumKey(P3Id.MoonOnTheCeiling), "A moon on the ceiling" },
		{ Set.EnumKey(P3Id.DangerousMoonPlanet), "Dangerous moon (planet)" },
		{ Set.EnumKey(P3Id.DangerousStar), "Dangerous star" },
		{ Set.EnumKey(P3Id.HugePaperWeight), "Huge paper weight" },
		{ Set.EnumKey(P3Id.StarByBurningWatchman), "Star by a burning watchman" },
		{ Set.EnumKey(P3Id.CraterCart), "Crater cart" },
		{ Set.EnumKey(P3Id.BlackContainerBalcony), "Black container balcon" },
		{ Set.EnumKey(P3Id.ThreeColoredContainer), "Three colored container" },
		{ Set.EnumKey(P3Id.BlueLightBalconyStatic), "Blue light balcony (static)" },
		{ Set.EnumKey(P3Id.ContainerWithoutOpening), "The container without an opening" },
		{ Set.EnumKey(P3Id.RedSquare), "Red square" },
		{ Set.EnumKey(P3Id.BunchOfBlackContainersAtBaseStatic), "A bunch of black containers at the base (static)" },
		{ Set.EnumKey(P3Id.BurningRockSeed), "Burning rock seed" },
		{ Set.EnumKey(P3Id.BetweenMachinesThreeLegs), "In between the machines with three legs" },
		{ Set.EnumKey(P3Id.VeryYellowPlatformStatic), "Very yellow platform (static)" }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string>();

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(MadSpace.PieceToHint, MadSpace.ImpossiblePieces);

	internal enum EnemyId {
		Watchman = 0x010A,
		EvilLiquid = 0x020A,
		BlueEnemy = 0x040A,
		MachineProtectsStorage = 0x050A
	}

	internal enum P1Id {
		RedLightBalcony = 0x0001,
		BluLightBalconyBlue = 0x0101,
		BlueLightBalconyYellow = 0x0201,
		BlackContainerBalcony = 0x0301,
		OctagonalMissileLaunchingPadNearRocket = 0x0401,
		OctagonalMissileLaunchingPadFarRocket = 0x0501,
		ThreeColoredContainerBlue = 0x0601,
		ThreeColoredContainerYellow = 0x0701,
		ContainerWithNoOpening = 0x0801,
		BlueLightCircle = 0x0901,
		GreenInABowl = 0x0A01,
		LonelyHouseCrystal = 0x0B01,
		TiltedLight = 0x0C01,
		LonelyHouseOmochao = 0x0D01,
		PropellorMachineThreeLegs = 0x0E01,
		Machine1ThreeLegs = 0x0F01,
		Machine3ThreeLegs = 0x1001,
		RedNail = 0x1101,
		No2Leg = 0x1201,
		YellowCircleCCW = 0x1301,
		YellowCircleCW = 0x1401,
		HouseMeteoritesOwner = 0x1501,
		WrongLight = 0x1601,
		TiredLight = 0x1701,
		ContainerNotFloating = 0x0003,
		ThreeColoredContainerRed = 0x0103,
		ContainerWithinContainer = 0x0203,
		BoxSurroundedByRedLights = 0x0303,
		ItsHotInside = 0x0403,
		DancingWoodenBoxGrass = 0x0603,
		BetweenTallGuys = 0x0703
	}

	internal enum P2Id {
		RedLightBalcony = 0x0000,
		JewelGrowingRockHigh = 0x0100,
		JewelGrowingRockLow = 0x0200,
		TopOfCapsuleTop = 0x0300,
		TopOfCapsuleBottom = 0x0400,
		FloatingPlatformGravityMeteoriteFarOpening = 0x0500,
		FloatingPlatformGravityMeteoriteNearOpening = 0x0600,
		ToCloseForestSeeTrees = 0x0700,
		FlyingContainerRed = 0x0002,
		FlyingContainerBlack = 0x0102,
		MessyStorage = 0x0202,
		ContainerWithinContainer = 0x0302,
		SpinningBoxAboveMeteorite = 0x0402,
		BetweenRedNails = 0x0502,
		BlueInYellow = 0x0005,
		StarUnderLight = 0x0105,
		StickingStarFarArk = 0x0205,
		StickingStarFarRocket = 0x0305,
		StickingStarNearArk = 0x0405,
		LightDidntGrowUp = 0x0505,
		SadAndLonelyLight = 0x0605,
		UnderBlackBox = 0x0705,
		TopLegMachine1 = 0x0805,
		TopLegMachine3 = 0x0905,
		LonelyStarPrairie = 0x0A05,
		StarUnderRoof = 0x0B05,
		WrongLight = 0x0C05,
		CrescentMoonGreenGlowing = 0x0E05,
		BetweenTwoMoons = 0x0F05
	}

	internal enum P3Id {
		WhereAllLightsGather = 0x0004,
		StickingStar = 0x0104,
		MoonBetweenSomething = 0x0204,
		OddMoon = 0x0304,
		StarRedLightShinesOn = 0x0404,
		DangerousMoonLarge = 0x0504,
		DangerousMoonSmall = 0x0604,
		BaseOfTiltedLight = 0x0804,
		LonelyLightInDark = 0x0904,
		MoonOnTheCeiling = 0x0A04,
		DangerousMoonPlanet = 0x0B04,
		DangerousStar = 0x0C04,
		HugePaperWeight = 0x0E04,
		StarByBurningWatchman = 0x0F04,
		CraterCart = 0x0007,
		BlackContainerBalcony = 0x0107,
		ThreeColoredContainer = 0x0207,
		BlueLightBalconyStatic = 0x0108,
		ContainerWithoutOpening = 0x0208,
		RedSquare = 0x0308,
		BunchOfBlackContainersAtBaseStatic = 0x0408,
		BurningRockSeed = 0x0508,
		BetweenMachinesThreeLegs = 0x0608,
		VeryYellowPlatformStatic = 0x0708
	}
}
