using sa2_hunting_teacher.Knuckles;

namespace sa2_hunting_teacher.Rouge;

public class SecurityHall(SA2Manager manager, byte repetitions) : HuntingLevel(manager, repetitions) {
	public override LevelId LevelId => LevelId.SecurityHall;

	protected override Set[] Sequence { get; } = [
		Set.Create(P1Id.PlaceWhereUseMostElectricityOpen, P2Id.AirConditionerUpper, P3Id.PlaceProtectedByLasersBlueA, SecurityHall.PieceToHint),
		Set.Create(P1Id.RidingOnTheB, EnemyId.PlaceWhereUseMostElectricityRight, P3Id.ThreeCylindersYellowA, SecurityHall.PieceToHint),
		Set.Create(EnemyId.TakingANap, P2Id.LonelyDoorYellow, P3Id.PiledUpContainersUpper, SecurityHall.PieceToHint),
		Set.Create(P1Id.UselessSafeBlueC, P2Id.TheLetterLRedB, P3Id.ShadyPlace, SecurityHall.PieceToHint),
		Set.Create(EnemyId.ProtectBlueHunter, EnemyId.LonelyAtWork, P3Id.NextToACardboardBox, SecurityHall.PieceToHint),
		Set.Create(P1Id.UselessSafeYellowB, EnemyId.AirConditionerHunter, P3Id.InTheAirC, SecurityHall.PieceToHint),
		Set.Create(EnemyId.OnBigBoxBack, P2Id.TwoColoredContainerLower, P3Id.SixSafes, SecurityHall.PieceToHint),
		Set.Create(P1Id.UnderUnbreakableContainer, P2Id.TheLetterLRedC, P3Id.NextoneIsEmptyA, SecurityHall.PieceToHint),
		Set.Create(EnemyId.PlaceWhereUseMostElectricityLeft, EnemyId.ProtectBlueRhino, P3Id.InvincibleGuard, SecurityHall.PieceToHint),
		Set.Create(P1Id.UselessSafeYellowC, P2Id.InAColdBox, P3Id.ThreeCylindersBlueC, SecurityHall.PieceToHint),
		Set.Create(EnemyId.OnBigBoxFront, P1Id.TwoContainersFacingEachOtherAirDuctC, P3Id.TheLetterLStatic, SecurityHall.PieceToHint),
		Set.Create(P1Id.UselessSafeBlueA, P2Id.NextToACardboardBox, P3Id.PiledUpContainersLower, SecurityHall.PieceToHint),
		Set.Create(P1Id.PlaceProtectedBySpikes, P2Id.NearLetterBox, P3Id.UselessBlank, SecurityHall.PieceToHint),
		Set.Create(P1Id.PlaceProtectedByLasers, P2Id.TheOneBelowIsEmptyBlueC, P3Id.AirConditioner, SecurityHall.PieceToHint),
		Set.Create(P1Id.AirConditionerBox, P2Id.HidingUpThereA, P3Id.PlaceProtectedByLasersMoving, SecurityHall.PieceToHint),
		Set.Create(P1Id.HidingUpThere, P2Id.LonelyDoorBlue, P3Id.TiltedLaser, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoContainersFacingEachOtherContainer, P2Id.ProtectBlueOpen, P3Id.PlaceProtectedByLasers, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerC, P2Id.TwoColoredContainerUpper, P3Id.TheLetterLMoving, SecurityHall.PieceToHint),
		Set.Create(P1Id.BlackAndYellowStripesBC, P2Id.NextToCardboardBoxes, P3Id.WithLotOfMoney, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerCenter, P2Id.TheOneAboveIsEmpty, P3Id.PlaceProtectedByLasersUpper, SecurityHall.PieceToHint),
		Set.Create(P1Id.RidingOnTheAB, P2Id.IfYouKickItGetMadTurnRedUpper, P3Id.CanSeeButCantGetItB, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerUpper, EnemyId.LostChild, P3Id.CanSeeButCantGetItSky, SecurityHall.PieceToHint),
		Set.Create(P1Id.UselessSafeBlueB, P2Id.AirConditionerTank, P3Id.ShowsUpOnceInWhile, SecurityHall.PieceToHint),
		Set.Create(P1Id.InTheTank, P2Id.HidingUpThereC, P3Id.TheNextOneIsEmptyB, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerFence, EnemyId.AirConditionerUpperRhino, P3Id.PlaceProtectedByLasersYellowA, SecurityHall.PieceToHint),
		Set.Create(P1Id.UselessSafeYellowA, P2Id.ThreeFootGap, P3Id.WithCardboardBox, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerAirDuct, P2Id.TheOneBelowIsEmptyRedA, P3Id.FloorAndAlsoCeiling, SecurityHall.PieceToHint),
		Set.Create(P1Id.CanSeeFromBotCantGetFromBot, EnemyId.AirConditionerLowerRhino, P3Id.InvisibleRingMarksSpot, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoContainersFacingEachOtherAirDuctA, P2Id.FloorAndAlsoCeiling, P3Id.RedX, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerWoodBox, P2Id.PlaceProtectedByLasersTank, P3Id.FloorAndAlsoCeiling, SecurityHall.PieceToHint),
		Set.Create(P1Id.ThreeCylinders, EnemyId.AirConditionerUpperRhino, P3Id.InTheAirA, SecurityHall.PieceToHint),
		Set.Create(EnemyId.EveryoneSeenAtLeastOnceBefore, P2Id.TheLetterLRedA, P3Id.CanSeeButCantGetItSky, SecurityHall.PieceToHint),
		Set.Create(P1Id.RidingOnTheAB, P2Id.PlaceProtectedByLasersChaoBox, P3Id.YellowRectangle, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoContainersFacingEachOtherAirDuctC, P2Id.UnderSquareAirDuctB, P3Id.WithLotOfMoney, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoContainersFacingEachOtherFenceA, P2Id.ProtectBlueOpen, P3Id.TheNextOneIsEmptyC, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerSteelBox, P2Id.TwoBlankLookingDownBelow, P3Id.PlaceProtectedByLasers, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerSteelBox, P2Id.TheLetterLBlue, P3Id.UselessBlank, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoContainersFacingEachOtherAirDuctC, P2Id.HidingUpThereB, P3Id.ThreeCylindersYellowA, SecurityHall.PieceToHint),
		Set.Create(P1Id.TheLetterL, P2Id.NextToCardboardBoxes, P3Id.YellowRectangle, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoColoredContainerWoodBox, P2Id.IfYouKickItGetMadTurnRedLower, P3Id.PlaceProtectedByLasersUpper, SecurityHall.PieceToHint),
		Set.Create(P1Id.BlackAndYellowStripesAB, P2Id.UnderSquareAirDuctC, P3Id.ShadyPlace, SecurityHall.PieceToHint),
		Set.Create(P1Id.PlaceWhereUseMostElectricityOpen, P2Id.LonelyDoorRed, P3Id.RedX, SecurityHall.PieceToHint),
		Set.Create(P1Id.TwoContainersFacingEachOtherFenceC, P2Id.AirConditionerTank, P3Id.FloorAndAlsoCeiling, SecurityHall.PieceToHint),
	];

	public override string ToString() => "Security Hall";

	public override Dictionary<int, string> PieceToHintInstance => SecurityHall.PieceToHint;
	public static Dictionary<int, string> PieceToHint { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(EnemyId.EveryoneSeenAtLeastOnceBefore), "Everyone has seen it at least once before..." },
		{ Set.EnumKey(EnemyId.LonelyAtWork), "Lonely at work." },
		{ Set.EnumKey(EnemyId.PlaceWhereUseMostElectricityLeft), "A place where you use the most electricity. (left)" },
		{ Set.EnumKey(EnemyId.PlaceWhereUseMostElectricityRight), "A place where you use the most electricity. (right)" },
		{ Set.EnumKey(EnemyId.AirConditionerLowerRhino), "Air conditioner of the Security Hall. (lower Rhino)" },
		{ Set.EnumKey(EnemyId.LostChild), "Lost child." },
		{ Set.EnumKey(EnemyId.ProtectBlueRhino), "Protect \"Blue\". (Rhino)" },
		{ Set.EnumKey(EnemyId.ProtectBlueHunter), "Protect \"Blue\". (Hunter)" },
		{ Set.EnumKey(EnemyId.OnBigBoxFront), "On a big box. (front)" },
		{ Set.EnumKey(EnemyId.OnBigBoxBack), "On a big box. (back)" },
		{ Set.EnumKey(EnemyId.TakingANap), "Taking a nap..." },
		{ Set.EnumKey(EnemyId.AirConditionerUpperRhino), "Air conditioner of the Security Hall. (upper Rhino)" },
		{ Set.EnumKey(EnemyId.AirConditionerHunter), "Air conditioner of the Security Hall. (Hunter)" },
		{ Set.EnumKey(P1Id.PlaceProtectedBySpikes), "A place which is protected by spikes." },
		{ Set.EnumKey(P1Id.UselessSafeYellowA), "Useless safe. (Yellow A)" },
		{ Set.EnumKey(P1Id.UselessSafeBlueA), "Useless safe. (Blue A)" },
		{ Set.EnumKey(P1Id.TwoContainersFacingEachOtherAirDuctA), "Two containers facing each other. (Air duct A)" },
		{ Set.EnumKey(P1Id.TwoColoredContainerSteelBox), "Two-colored container. (steel box)" },
		{ Set.EnumKey(P1Id.PlaceProtectedByLasers), "A place which is protected by lasers." },
		{ Set.EnumKey(P1Id.TwoContainersFacingEachOtherFenceA), "Two containers facing each other. (fence A)" },
		{ Set.EnumKey(P1Id.HidingUpThere), "Hiding up there..." },
		{ Set.EnumKey(P1Id.UselessSafeYellowB), "Useless safe. (Yellow B)" },
		{ Set.EnumKey(P1Id.UselessSafeBlueB), "Useless safe. (Blue B)" },
		{ Set.EnumKey(P1Id.RidingOnTheB), "Riding on the ____? (B)" },
		{ Set.EnumKey(P1Id.RidingOnTheAB), "Riding on the ____? (A/B)" },
		{ Set.EnumKey(P1Id.UnderUnbreakableContainer), "Under the unbreakable container." },
		{ Set.EnumKey(P1Id.BlackAndYellowStripesAB), "Black and yellow stripes. (A/B)" },
		{ Set.EnumKey(P1Id.CanSeeFromBotCantGetFromBot), "You can see it from the bottom but can't get to it from the bottom." },
		{ Set.EnumKey(P1Id.TwoColoredContainerCenter), "Two-colored container. (center)" },
		{ Set.EnumKey(P1Id.UselessSafeBlueC), "Useless safe. (Blue C)" },
		{ Set.EnumKey(P1Id.UselessSafeYellowC), "Useless safe. (Yellow C)" },
		{ Set.EnumKey(P1Id.PlaceWhereUseMostElectricityOpen), "A place where you use the most electricity. (open)" },
		{ Set.EnumKey(P1Id.TwoContainersFacingEachOtherAirDuctC), "Two containers facing each other. (air duct C)" },
		{ Set.EnumKey(P1Id.ThreeCylinders), "Three cylinders." },
		{ Set.EnumKey(P1Id.TwoColoredContainerC), "Two-colored container. (C)" },
		{ Set.EnumKey(P1Id.BlackAndYellowStripesBC), "Black and yellow stripes. (B/C)" },
		{ Set.EnumKey(P1Id.TwoContainersFacingEachOtherFenceC), "Two containers facing each other. (fence C)" },
		{ Set.EnumKey(P1Id.InTheTank), "In the tank." },
		{ Set.EnumKey(P1Id.TwoColoredContainerUpper), "Two-colored container. (upper)" },
		{ Set.EnumKey(P1Id.TwoColoredContainerWoodBox), "Two-colored container. (wood box)" },
		{ Set.EnumKey(P1Id.TwoContainersFacingEachOtherContainer), "Two containers facing each other. (container)" },
		{ Set.EnumKey(P1Id.TwoColoredContainerAirDuct), "Two-colored container. (air duct)" },
		{ Set.EnumKey(P1Id.TwoColoredContainerFence), "Two-colored container. (fence)" },
		{ Set.EnumKey(P1Id.AirConditionerBox), "Air conditioner of the Security Hall. (box)" },
		{ Set.EnumKey(P1Id.TheLetterL), "The letter \"L\"." },
		{ Set.EnumKey(P2Id.ProtectBlueOpen), "Protect \"Blue\". (open)" },
		{ Set.EnumKey(P2Id.AirConditionerUpper), "Air conditioner of the Security Hall. (upper)" },
		{ Set.EnumKey(P2Id.PlaceProtectedByLasersChaoBox), "A place which is protected by lasers. (Chao box)" },
		{ Set.EnumKey(P2Id.HidingUpThereA), "Hiding up there... (A)" },
		{ Set.EnumKey(P2Id.HidingUpThereB), "Hiding up there... (B)" },
		{ Set.EnumKey(P2Id.FloorAndAlsoCeiling), "It's a floor and also a ceiling." },
		{ Set.EnumKey(P2Id.HidingUpThereC), "Hiding up there... (C)" },
		{ Set.EnumKey(P2Id.ThreeFootGap), "A three-foot gap." },
		{ Set.EnumKey(P2Id.IfYouKickItGetMadTurnRedUpper), "If you kick it, it will get very mad and turn red. (upper)" },
		{ Set.EnumKey(P2Id.TwoColoredContainerUpper), "Two-colored container. (upper)" },
		{ Set.EnumKey(P2Id.TwoColoredContainerLower), "Two-colored container. (lower)" },
		{ Set.EnumKey(P2Id.AirConditionerTank), "Air conditioner of the Security Hall. (tank)" },
		{ Set.EnumKey(P2Id.TwoBlankLookingDownBelow), "Two ____ looking down below..." },
		// { Set.EnumKey(P2Id.PlaceProtectedByLasersCenterImpossible), "A place which is protected by lasers. (center)" },
		{ Set.EnumKey(P2Id.IfYouKickItGetMadTurnRedLower), "If you kick it, it will get very mad and turn red. (lower)" },
		{ Set.EnumKey(P2Id.PlaceProtectedByLasersTank), "A place which is protected by lasers. (tank)" },
		{ Set.EnumKey(P2Id.TheLetterLRedA), "The letter \"L\". (Red A)" },
		{ Set.EnumKey(P2Id.TheOneBelowIsEmptyRedA), "The one below is empty. (Red A)" },
		{ Set.EnumKey(P2Id.TheOneAboveIsEmpty), "The one above is empty." },
		{ Set.EnumKey(P2Id.NextToCardboardBoxes), "Next to the cardboard boxes." },
		{ Set.EnumKey(P2Id.InAColdBox), "In a cold box." },
		{ Set.EnumKey(P2Id.NearLetterBox), "Near the letter box." },
		{ Set.EnumKey(P2Id.LonelyDoorBlue), "Lonely door. (Blue)" },
		{ Set.EnumKey(P2Id.LonelyDoorYellow), "Lonely door. (Yellow)" },
		{ Set.EnumKey(P2Id.TheLetterLRedB), "The letter \"L\". (Red B)" },
		{ Set.EnumKey(P2Id.LonelyDoorRed), "Lonely door. (Red)" },
		{ Set.EnumKey(P2Id.UnderSquareAirDuctB), "Under the square air duct. (B)" },
		{ Set.EnumKey(P2Id.TheLetterLRedC), "The letter \"L\". (Red C)" },
		{ Set.EnumKey(P2Id.NextToACardboardBox), "Next to a cardboard box." },
		{ Set.EnumKey(P2Id.UnderSquareAirDuctC), "Under the square air duct. (C)" },
		{ Set.EnumKey(P2Id.TheOneBelowIsEmptyBlueC), "The one below is empty. (Blue C)" },
		{ Set.EnumKey(P2Id.TheLetterLBlue), "The letter \"L\". (Blue)" },
		{ Set.EnumKey(P3Id.PiledUpContainersUpper), "Piled up containers. (upper)" },
		{ Set.EnumKey(P3Id.FloorAndAlsoCeiling), "It's a floor and also a ceiling." },
		{ Set.EnumKey(P3Id.TheLetterLStatic), "The letter \"L\". (static)" },
		{ Set.EnumKey(P3Id.NextoneIsEmptyA), "The next one is empty. (A)" },
		{ Set.EnumKey(P3Id.ThreeCylindersYellowA), "Three cylinders. (Yellow A)" },
		{ Set.EnumKey(P3Id.PlaceProtectedByLasersYellowA), "A place which is protected by lasers. (Yellow A)" },
		{ Set.EnumKey(P3Id.CanSeeButCantGetItB), "You can see it but you can't get it. (B)" },
		{ Set.EnumKey(P3Id.SixSafes), "Six safes." },
		{ Set.EnumKey(P3Id.PiledUpContainersLower), "Piled up containers. (lower)" },
		{ Set.EnumKey(P3Id.WithCardboardBox), "With a cardboard box." },
		{ Set.EnumKey(P3Id.CanSeeButCantGetItSky), "You can see it but you can't get it. (sky)" },
		{ Set.EnumKey(P3Id.PlaceProtectedByLasers), "A place which is protected lasers." },
		{ Set.EnumKey(P3Id.ThreeCylindersBlueC), "Three cylinders. (Blue C)" },
		{ Set.EnumKey(P3Id.InvisibleRingMarksSpot), "Invisible rings mark the spot." },
		{ Set.EnumKey(P3Id.UselessBlank), "Useless ____." },
		{ Set.EnumKey(P3Id.AirConditioner), "Air conditioner of the Security Hall." },
		{ Set.EnumKey(P3Id.InvincibleGuard), "Invincible guard." },
		{ Set.EnumKey(P3Id.PlaceProtectedByLasersMoving), "A place which is protected by lasers. (moving)" },
		{ Set.EnumKey(P3Id.RedX), "Red \"X\"." },
		{ Set.EnumKey(P3Id.ShowsUpOnceInWhile), "Shows up once in a while." },
		{ Set.EnumKey(P3Id.WithLotOfMoney), "With a lot of money." },
		{ Set.EnumKey(P3Id.YellowRectangle), "Yellow rectangle." },
		{ Set.EnumKey(P3Id.TiltedLaser), "Tilted laser." },
		{ Set.EnumKey(P3Id.TheLetterLMoving), "The letter \"L\". (moving)" },
		{ Set.EnumKey(P3Id.PlaceProtectedByLasersUpper), "A place which is protected by lasers. (upper)" },
		{ Set.EnumKey(P3Id.ShadyPlace), "A shady place." },
		{ Set.EnumKey(P3Id.InTheAirA), "In the air. (A)" },
		{ Set.EnumKey(P3Id.PlaceProtectedByLasersBlueA), "A place which is protected by lasers. (Blue A)" },
		{ Set.EnumKey(P3Id.NextToACardboardBox), "Next to the a cardboard box." },
		{ Set.EnumKey(P3Id.TheNextOneIsEmptyB), "The next one is empty. (B)" },
		{ Set.EnumKey(P3Id.InTheAirC), "In the air. (C)" },
		{ Set.EnumKey(P3Id.TheNextOneIsEmptyC), "The next one is empty. (C)" }
	};

	public static Dictionary<int, string> ImpossiblePieces { get; } = new Dictionary<int, string> {
		{ Set.EnumKey(P2Id.PlaceProtectedByLasersCenterImpossible), "A place which is protected by lasers. (center)" }
	};

	public static LevelCatalog Catalog { get; } = LevelCatalog.Build<P1Id, P2Id, P3Id, EnemyId>(SecurityHall.PieceToHint, SecurityHall.ImpossiblePieces);

	internal enum EnemyId {
		EveryoneSeenAtLeastOnceBefore = 0x000A,
		LonelyAtWork = 0x010A,
		PlaceWhereUseMostElectricityLeft = 0x020A,
		PlaceWhereUseMostElectricityRight = 0x030A,
		AirConditionerLowerRhino = 0x050A,
		LostChild = 0x060A,
		ProtectBlueRhino = 0x070A,
		ProtectBlueHunter = 0x080A,
		OnBigBoxFront = 0x090A,
		OnBigBoxBack = 0x0A0A,
		TakingANap = 0x0B0A,
		AirConditionerUpperRhino = 0x0C0A,
		AirConditionerHunter = 0x0D0A
	}

	internal enum P1Id {
		PlaceProtectedBySpikes = 0x0001,
		UselessSafeYellowA = 0x0101,
		UselessSafeBlueA = 0x0201,
		TwoContainersFacingEachOtherAirDuctA = 0x0301,
		TwoColoredContainerSteelBox = 0x0401,
		PlaceProtectedByLasers = 0x0501,
		TwoContainersFacingEachOtherFenceA = 0x0601,
		HidingUpThere = 0x0701,
		UselessSafeYellowB = 0x0801,
		UselessSafeBlueB = 0x0901,
		RidingOnTheB = 0x0A01,
		RidingOnTheAB = 0x0B01,
		UnderUnbreakableContainer = 0x0C01,
		BlackAndYellowStripesAB = 0x0D01,
		CanSeeFromBotCantGetFromBot = 0x0E01,
		TwoColoredContainerCenter = 0x0F01,
		UselessSafeBlueC = 0x1001,
		UselessSafeYellowC = 0x1101,
		PlaceWhereUseMostElectricityOpen = 0x1201,
		TwoContainersFacingEachOtherAirDuctC = 0x1301,
		ThreeCylinders = 0x1401,
		TwoColoredContainerC = 0x1501,
		BlackAndYellowStripesBC = 0x1601,
		TwoContainersFacingEachOtherFenceC = 0x1701,
		InTheTank = 0x0003,
		TwoColoredContainerUpper = 0x0103,
		TwoColoredContainerWoodBox = 0x0203,
		TwoContainersFacingEachOtherContainer = 0x0303,
		TwoColoredContainerAirDuct = 0x0403,
		TwoColoredContainerFence = 0x0503,
		AirConditionerBox = 0x0603,
		TheLetterL = 0x0703
	}

	internal enum P2Id {
		ProtectBlueOpen = 0x0000,
		AirConditionerUpper = 0x0100,
		PlaceProtectedByLasersChaoBox = 0x0200,
		HidingUpThereA = 0x0300,
		HidingUpThereB = 0x0400,
		FloorAndAlsoCeiling = 0x0500,
		HidingUpThereC = 0x0600,
		ThreeFootGap = 0x0700,
		IfYouKickItGetMadTurnRedUpper = 0x0002,
		TwoColoredContainerUpper = 0x0102,
		TwoColoredContainerLower = 0x0202,
		AirConditionerTank = 0x0302,
		TwoBlankLookingDownBelow = 0x0402,
		PlaceProtectedByLasersCenterImpossible = 0x0502, // Impossible Piece
		IfYouKickItGetMadTurnRedLower = 0x0602,
		PlaceProtectedByLasersTank = 0x0702,
		TheLetterLRedA = 0x0005,
		TheOneBelowIsEmptyRedA = 0x0105,
		TheOneAboveIsEmpty = 0x0205,
		NextToCardboardBoxes = 0x0305,
		InAColdBox = 0x0405,
		NearLetterBox = 0x0505,
		LonelyDoorBlue = 0x0605,
		LonelyDoorYellow = 0x0705,
		TheLetterLRedB = 0x0805,
		LonelyDoorRed = 0x0905,
		UnderSquareAirDuctB = 0x0A05,
		TheLetterLRedC = 0x0B05,
		NextToACardboardBox = 0x0C05,
		UnderSquareAirDuctC = 0x0D05,
		TheOneBelowIsEmptyBlueC = 0x0E05,
		TheLetterLBlue = 0x0F05
	}

	internal enum P3Id {
		PiledUpContainersUpper = 0x0004,
		FloorAndAlsoCeiling = 0x0104,
		TheLetterLStatic = 0x0204,
		NextoneIsEmptyA = 0x0304,
		ThreeCylindersYellowA = 0x0404,
		PlaceProtectedByLasersYellowA = 0x0504,
		CanSeeButCantGetItB = 0x0604,
		SixSafes = 0x0704,
		PiledUpContainersLower = 0x0804,
		WithCardboardBox = 0x0904,
		CanSeeButCantGetItSky = 0x0A04,
		PlaceProtectedByLasers = 0x0B04,
		ThreeCylindersBlueC = 0x0C04,
		InvisibleRingMarksSpot = 0x0D04,
		UselessBlank = 0x0E04,
		AirConditioner = 0x0F04,
		InvincibleGuard = 0x0007,
		PlaceProtectedByLasersMoving = 0x0107,
		RedX = 0x0207,
		ShowsUpOnceInWhile = 0x0307,
		WithLotOfMoney = 0x0407,
		YellowRectangle = 0x0507,
		TiltedLaser = 0x0607,
		TheLetterLMoving = 0x0707,
		PlaceProtectedByLasersUpper = 0x0008,
		ShadyPlace = 0x0108,
		InTheAirA = 0x0208,
		PlaceProtectedByLasersBlueA = 0x0308,
		NextToACardboardBox = 0x0408,
		TheNextOneIsEmptyB = 0x0508,
		InTheAirC = 0x0608,
		TheNextOneIsEmptyC = 0x0708
	}
}
